/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 10:54:33 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.rpt;

import java.io.Serializable;

/**
 * A class that represents a row in the APPROVER_SUSPEND_REPORT table. 
 * You can customize the behavior of this class by editing the class, {@link ApproverSuspendReport()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractApproverSuspendReport 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String reportId;

    /** The value of the simple transId property. */
    private java.lang.String transId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple transType property. */
    private java.lang.String transType;

    /** The value of the simple subType property. */
    private java.lang.String subType;

    /** The value of the simple operationType property. */
    private java.lang.String operationType;

    /** The value of the simple originalStatus property. */
    private java.lang.String originalStatus;

    /**
     * Simple constructor of AbstractApproverSuspendReport instances.
     */
    public AbstractApproverSuspendReport()
    {
    }

    /**
     * Constructor of AbstractApproverSuspendReport instances given a simple primary key.
     * @param reportId
     */
    public AbstractApproverSuspendReport(java.lang.String reportId)
    {
        this.setReportId(reportId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getReportId()
    {
        return reportId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param reportId
     */
    public void setReportId(java.lang.String reportId)
    {
        this.hashValue = 0;
        this.reportId = reportId;
    }

    /**
     * Return the value of the TRANS_ID column.
     * @return java.lang.String
     */
    public java.lang.String getTransId()
    {
        return this.transId;
    }

    /**
     * Set the value of the TRANS_ID column.
     * @param transId
     */
    public void setTransId(java.lang.String transId)
    {
        this.transId = transId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the TRANS_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getTransType()
    {
        return this.transType;
    }

    /**
     * Set the value of the TRANS_TYPE column.
     * @param transType
     */
    public void setTransType(java.lang.String transType)
    {
        this.transType = transType;
    }

    /**
     * Return the value of the OPERATION_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getOperationType()
    {
        return this.operationType;
    }

    /**
     * Set the value of the OPERATION_TYPE column.
     * @param operationType
     */
    public void setOperationType(java.lang.String operationType)
    {
        this.operationType = operationType;
    }

    /**
     * Return the value of the ORIGINAL_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getOriginalStatus()
    {
        return this.originalStatus;
    }

    /**
     * Set the value of the ORIGINAL_STATUS column.
     * @param originalStatus
     */
    public void setOriginalStatus(java.lang.String originalStatus)
    {
        this.originalStatus = originalStatus;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof ApproverSuspendReport))
            return false;
        ApproverSuspendReport that = (ApproverSuspendReport) rhs;
        if (this.getReportId() == null || that.getReportId() == null)
            return false;
        return (this.getReportId().equals(that.getReportId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int reportIdValue = this.getReportId() == null ? 0 : this.getReportId().hashCode();
            result = result * 37 + reportIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public java.lang.String getSubType() {
		return subType;
	}

	public void setSubType(java.lang.String subType) {
		this.subType = subType;
	}
}
