package app.cib.bo.srv;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * Message generated by MyEclipse - Hibernate Tools
 */
public class Message extends AbstractMessage implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Message() {
    }

	/** minimal constructor */
    public Message(String messageId) {
        super(messageId);
    }

}
