/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Sep 13 14:41:45 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.txn;

import java.io.Serializable;

/**
 * A class that represents a row in the TRANSFER_MACAU table. 
 * You can customize the behavior of this class by editing the class, {@link TransferMacau()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTransferMacau 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String transId;

    /** The value of the simple recordType property. */
    private java.lang.String recordType;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple fromAccount property. */
    private java.lang.String fromAccount;

    /** The value of the simple toAccount property. */
    private java.lang.String toAccount;

    /** The value of the simple beneficiaryName1 property. */
    private java.lang.String beneficiaryName1;

    /** The value of the simple beneficiaryName2 property. */
    private java.lang.String beneficiaryName2;

    /** The value of the simple beneficiaryBank property. */
    private java.lang.String beneficiaryBank;

    /** The value of the simple transferAmount property. */
    private java.lang.Double transferAmount;

    /** The value of the simple debitAmount property. */
    private java.lang.Double debitAmount;

    /** The value of the simple requestType property. */
    private java.lang.String requestType;

    /** The value of the simple transferDate property. */
    private java.util.Date transferDate;

    /** The value of the simple chargeBy property. */
    private java.lang.String chargeBy;

    /** The value of the simple chargeAccount property. */
    private java.lang.String chargeAccount;

    /** The value of the simple messsage property. */
    private java.lang.String messsage;

    /** The value of the simple messsage2 property. */
    private java.lang.String messsage2;
    
    /** The value of the simple messsage3 property. */
    private java.lang.String messsage3;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple requestTime property. */
    private java.util.Date requestTime;

    /** The value of the simple executeTime property. */
    private java.util.Date executeTime;

    /** The value of the simple status property. */
    private java.lang.String status;
    private java.lang.String inputAmountFlag;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple toCurrency property. */
    private java.lang.String toCurrency;

    /** The value of the simple fromCurrency property. */
    private java.lang.String fromCurrency;

    /** The value of the simple chargeAmount property. */
    private java.lang.Double chargeAmount;

    /** The value of the simple exchangeRate property. */
    private java.lang.Double exchangeRate;

    /** The value of the simple chargeCurrency property. */
    private java.lang.String chargeCurrency;

    /** The value of the simple commissionAmount property. */
    private java.lang.Double commissionAmount;

    /** The value of the simple taxAmount property. */
    private java.lang.Double taxAmount;

    /** The value of the simple handlingAmount property. */
    private java.lang.Double handlingAmount;

    /** The value of the simple swiftAmount property. */
    private java.lang.Double swiftAmount;

    /** The value of the simple chargeOur property. */
    private java.lang.Double chargeOur;
    
    private java.lang.String hostresponseCode;
    private java.lang.String hosterrorCode;

	/* Add by heyongjiang 20100804 */
    private java.lang.String purposeCode;
    private java.lang.String otherPurpose;
    private java.lang.String proofOfPurpose;
    
    private java.lang.String endDate;   //add by heyj 20190529
    
    private java.lang.String serialNumber;  //add by lzg 20190613
    
    private java.lang.Double showExchangeRate; //add by lzg 20190618
    
    public java.lang.Double getShowExchangeRate() {
		return showExchangeRate;
	}

	public void setShowExchangeRate(java.lang.Double showExchangeRate) {
		this.showExchangeRate = showExchangeRate;
	}

	public java.lang.String getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		this.serialNumber = serialNumber;
	}
    
    public java.lang.String getEndDate() {
		return endDate;
	}

	public void setEndDate(java.lang.String endDate) {
		this.endDate = endDate;
	}

	public java.lang.String getPurposeCode() {
		return purposeCode;
	}

	public void setPurposeCode(java.lang.String purposeCode) {
		this.purposeCode = purposeCode;
	}

	public java.lang.String getOtherPurpose() {
		return otherPurpose;
	}

	public void setOtherPurpose(java.lang.String otherPurpose) {
		this.otherPurpose = otherPurpose;
	}

	public java.lang.String getProofOfPurpose() {
		return proofOfPurpose;
	}

	public void setProofOfPurpose(java.lang.String proofOfPurpose) {
		this.proofOfPurpose = proofOfPurpose;
	}
	/* Add by heyongjiang end 20100804 */

	/**
     * Simple constructor of AbstractTransferMacau instances.
     */
    public AbstractTransferMacau()
    {
    }

    /**
     * Constructor of AbstractTransferMacau instances given a simple primary key.
     * @param transId
     */
    public AbstractTransferMacau(java.lang.String transId)
    {
        this.setTransId(transId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getTransId()
    {
        return transId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param transId
     */
    public void setTransId(java.lang.String transId)
    {
        this.hashValue = 0;
        this.transId = transId;
    }

    /**
     * Return the value of the RECORD_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getRecordType()
    {
        return this.recordType;
    }

    /**
     * Set the value of the RECORD_TYPE column.
     * @param recordType
     */
    public void setRecordType(java.lang.String recordType)
    {
        this.recordType = recordType;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the FROM_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getFromAccount()
    {
        return this.fromAccount;
    }

    /**
     * Set the value of the FROM_ACCOUNT column.
     * @param fromAccount
     */
    public void setFromAccount(java.lang.String fromAccount)
    {
        this.fromAccount = fromAccount;
    }

    /**
     * Return the value of the TO_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getToAccount()
    {
        return this.toAccount;
    }

    /**
     * Set the value of the TO_ACCOUNT column.
     * @param toAccount
     */
    public void setToAccount(java.lang.String toAccount)
    {
        this.toAccount = toAccount;
    }

    /**
     * Return the value of the BENEFICIARY_NAME1 column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryName1()
    {
        return this.beneficiaryName1;
    }

    /**
     * Set the value of the BENEFICIARY_NAME1 column.
     * @param beneficiaryName1
     */
    public void setBeneficiaryName1(java.lang.String beneficiaryName1)
    {
        this.beneficiaryName1 = beneficiaryName1;
    }

    /**
     * Return the value of the BENEFICIARY_NAME2 column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryName2()
    {
        return this.beneficiaryName2;
    }

    /**
     * Set the value of the BENEFICIARY_NAME2 column.
     * @param beneficiaryName2
     */
    public void setBeneficiaryName2(java.lang.String beneficiaryName2)
    {
        this.beneficiaryName2 = beneficiaryName2;
    }

    /**
     * Return the value of the BENEFICIARY_BANK column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryBank()
    {
        return this.beneficiaryBank;
    }

    /**
     * Set the value of the BENEFICIARY_BANK column.
     * @param beneficiaryBank
     */
    public void setBeneficiaryBank(java.lang.String beneficiaryBank)
    {
        this.beneficiaryBank = beneficiaryBank;
    }

    /**
     * Return the value of the TRANSFER_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getTransferAmount()
    {
        return this.transferAmount;
    }

    /**
     * Set the value of the TRANSFER_AMOUNT column.
     * @param transferAmount
     */
    public void setTransferAmount(java.lang.Double transferAmount)
    {
        this.transferAmount = transferAmount;
    }

    /**
     * Return the value of the DEBIT_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getDebitAmount()
    {
        return this.debitAmount;
    }

    /**
     * Set the value of the DEBIT_AMOUNT column.
     * @param debitAmount
     */
    public void setDebitAmount(java.lang.Double debitAmount)
    {
        this.debitAmount = debitAmount;
    }

    /**
     * Return the value of the REQUEST_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getRequestType()
    {
        return this.requestType;
    }

    /**
     * Set the value of the REQUEST_TYPE column.
     * @param requestType
     */
    public void setRequestType(java.lang.String requestType)
    {
        this.requestType = requestType;
    }

    /**
     * Return the value of the TRANSFER_DATE column.
     * @return java.util.Date
     */
    public java.util.Date getTransferDate()
    {
        return this.transferDate;
    }

    /**
     * Set the value of the TRANSFER_DATE column.
     * @param transferDate
     */
    public void setTransferDate(java.util.Date transferDate)
    {
        this.transferDate = transferDate;
    }

    /**
     * Return the value of the CHARGE_BY column.
     * @return java.lang.String
     */
    public java.lang.String getChargeBy()
    {
        return this.chargeBy;
    }

    /**
     * Set the value of the CHARGE_BY column.
     * @param chargeBy
     */
    public void setChargeBy(java.lang.String chargeBy)
    {
        this.chargeBy = chargeBy;
    }

    /**
     * Return the value of the CHARGE_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getChargeAccount()
    {
        return this.chargeAccount;
    }

    /**
     * Set the value of the CHARGE_ACCOUNT column.
     * @param chargeAccount
     */
    public void setChargeAccount(java.lang.String chargeAccount)
    {
        this.chargeAccount = chargeAccount;
    }

    /**
     * Return the value of the MESSSAGE column.
     * @return java.lang.String
     */
    public java.lang.String getMesssage()
    {
        return this.messsage;
    }

    /**
     * Set the value of the MESSSAGE column.
     * @param messsage
     */
    public void setMesssage(java.lang.String messsage)
    {
        this.messsage = messsage;
    }

    /**
     * Return the value of the MESSSAGE2 column.
     * @return java.lang.String
     */
    public java.lang.String getMesssage2()
    {
        return this.messsage2;
    }

    /**
     * Set the value of the MESSSAGE2 column.
     * @param messsage2
     */
    public void setMesssage2(java.lang.String messsage2)
    {
        this.messsage2 = messsage2;
    }
    
    public java.lang.String getMesssage3() {
		return messsage3;
	}

	public void setMesssage3(java.lang.String messsage3) {
		this.messsage3 = messsage3;
	}

	/**
     * Return the value of the REMARK column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the REQUEST_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getRequestTime()
    {
        return this.requestTime;
    }

    /**
     * Set the value of the REQUEST_TIME column.
     * @param requestTime
     */
    public void setRequestTime(java.util.Date requestTime)
    {
        this.requestTime = requestTime;
    }

    /**
     * Return the value of the EXECUTE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getExecuteTime()
    {
        return this.executeTime;
    }

    /**
     * Set the value of the EXECUTE_TIME column.
     * @param executeTime
     */
    public void setExecuteTime(java.util.Date executeTime)
    {
        this.executeTime = executeTime;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    public java.lang.String getInputAmountFlag()
    {
        return this.inputAmountFlag;
    }
    
    public void setInputAmountFlag(java.lang.String inputAmountFlag)
    {
        this.inputAmountFlag = inputAmountFlag;
    }
    
    
    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the TO_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getToCurrency()
    {
        return this.toCurrency;
    }

    /**
     * Set the value of the TO_CURRENCY column.
     * @param toCurrency
     */
    public void setToCurrency(java.lang.String toCurrency)
    {
        this.toCurrency = toCurrency;
    }

    /**
     * Return the value of the FROM_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getFromCurrency()
    {
        return this.fromCurrency;
    }

    /**
     * Set the value of the FROM_CURRENCY column.
     * @param fromCurrency
     */
    public void setFromCurrency(java.lang.String fromCurrency)
    {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Return the value of the CHARGE_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getChargeAmount()
    {
        return this.chargeAmount;
    }

    /**
     * Set the value of the CHARGE_AMOUNT column.
     * @param chargeAmount
     */
    public void setChargeAmount(java.lang.Double chargeAmount)
    {
        this.chargeAmount = chargeAmount;
    }

    /**
     * Return the value of the EXCHANGE_RATE column.
     * @return java.lang.Double
     */
    public java.lang.Double getExchangeRate()
    {
        return this.exchangeRate;
    }

    /**
     * Set the value of the EXCHANGE_RATE column.
     * @param exchangeRate
     */
    public void setExchangeRate(java.lang.Double exchangeRate)
    {
        this.exchangeRate = exchangeRate;
    }

    /**
     * Return the value of the CHARGE_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getChargeCurrency()
    {
        return this.chargeCurrency;
    }

    /**
     * Set the value of the CHARGE_CURRENCY column.
     * @param chargeCurrency
     */
    public void setChargeCurrency(java.lang.String chargeCurrency)
    {
        this.chargeCurrency = chargeCurrency;
    }

    /**
     * Return the value of the COMMISSION_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getCommissionAmount()
    {
        return this.commissionAmount;
    }

    /**
     * Set the value of the COMMISSION_AMOUNT column.
     * @param commissionAmount
     */
    public void setCommissionAmount(java.lang.Double commissionAmount)
    {
        this.commissionAmount = commissionAmount;
    }

    /**
     * Return the value of the TAX_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getTaxAmount()
    {
        return this.taxAmount;
    }

    /**
     * Set the value of the TAX_AMOUNT column.
     * @param taxAmount
     */
    public void setTaxAmount(java.lang.Double taxAmount)
    {
        this.taxAmount = taxAmount;
    }

    /**
     * Return the value of the HANDLING_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getHandlingAmount()
    {
        return this.handlingAmount;
    }

    /**
     * Set the value of the HANDLING_AMOUNT column.
     * @param handlingAmount
     */
    public void setHandlingAmount(java.lang.Double handlingAmount)
    {
        this.handlingAmount = handlingAmount;
    }

    /**
     * Return the value of the SWIFT_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getSwiftAmount()
    {
        return this.swiftAmount;
    }

    /**
     * Set the value of the SWIFT_AMOUNT column.
     * @param swiftAmount
     */
    public void setSwiftAmount(java.lang.Double swiftAmount)
    {
        this.swiftAmount = swiftAmount;
    }

    /**
     * Return the value of the CHARGE_OUR column.
     * @return java.lang.Double
     */
    public java.lang.Double getChargeOur()
    {
        return this.chargeOur;
    }

    /**
     * Set the value of the CHARGE_OUR column.
     * @param chargeOur
     */
    public void setChargeOur(java.lang.Double chargeOur)
    {
        this.chargeOur = chargeOur;
    }
    
    public java.lang.String getHostresponseCode()
    {
        return this.hostresponseCode;
    }
    public void setHostresponseCode(java.lang.String hostresponseCode)
    {
        this.hostresponseCode = hostresponseCode;
    }
    
    public java.lang.String getHosterrorCode()
    {
        return this.hosterrorCode;
    }
    public void setHosterrorCode(java.lang.String hosterrorCode)
    {
        this.hosterrorCode = hosterrorCode;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TransferMacau))
            return false;
        TransferMacau that = (TransferMacau) rhs;
        if (this.getTransId() == null || that.getTransId() == null)
            return false;
        return (this.getTransId().equals(that.getTransId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int transIdValue = this.getTransId() == null ? 0 : this.getTransId().hashCode();
            result = result * 37 + transIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

}
