/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Dec 08 17:07:40 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.txn;

import java.io.Serializable;

/**
 * A class that represents a row in the TXN_SIGN_DATA table.
 * You can customize the behavior of this class by editing the class, {@link TxnSignData()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTxnSignData
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String seqNo;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple userName property. */
    private java.lang.String userName;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple certAltName property. */
    private java.lang.String certAltName;

    /** The value of the simple certDn property. */
    private java.lang.String certDn;

    /** The value of the simple action property. */
    private java.lang.String action;

    /** The value of the simple workId property. */
    private java.lang.String workId;

    /** The value of the simple procId property. */
    private java.lang.String procId;

    /** The value of the simple txnType property. */
    private java.lang.String txnType;

    /** The value of the simple transId property. */
    private java.lang.String transId;

    /** The value of the simple signFields property. */
    private java.lang.String signFields;

    /** The value of the simple signData property. */
    private java.lang.String signData;

    /** The value of the simple signResult property. */
    private java.lang.String signResult;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple actionTime property. */
    private java.util.Date actionTime;

    /** The value of the simple actionResult property. */
    private java.lang.String actionResult;

    /**
     * Simple constructor of AbstractTxnSignData instances.
     */
    public AbstractTxnSignData()
    {
    }

    /**
     * Constructor of AbstractTxnSignData instances given a simple primary key.
     * @param seqNo
     */
    public AbstractTxnSignData(java.lang.String seqNo)
    {
        this.setSeqNo(seqNo);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getSeqNo()
    {
        return seqNo;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param seqNo
     */
    public void setSeqNo(java.lang.String seqNo)
    {
        this.hashValue = 0;
        this.seqNo = seqNo;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the USER_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getUserName()
    {
        return this.userName;
    }

    /**
     * Set the value of the USER_NAME column.
     * @param userName
     */
    public void setUserName(java.lang.String userName)
    {
        this.userName = userName;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the CERT_ALT_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getCertAltName()
    {
        return this.certAltName;
    }

    /**
     * Set the value of the CERT_ALT_NAME column.
     * @param certAltName
     */
    public void setCertAltName(java.lang.String certAltName)
    {
        this.certAltName = certAltName;
    }

    /**
     * Return the value of the CERT_DN column.
     * @return java.lang.String
     */
    public java.lang.String getCertDn()
    {
        return this.certDn;
    }

    /**
     * Set the value of the CERT_DN column.
     * @param certDn
     */
    public void setCertDn(java.lang.String certDn)
    {
        this.certDn = certDn;
    }

    /**
     * Return the value of the ACTION column.
     * @return java.lang.String
     */
    public java.lang.String getAction()
    {
        return this.action;
    }

    /**
     * Set the value of the ACTION column.
     * @param action
     */
    public void setAction(java.lang.String action)
    {
        this.action = action;
    }

    /**
     * Return the value of the WORK_ID column.
     * @return java.lang.String
     */
    public java.lang.String getWorkId()
    {
        return this.workId;
    }

    /**
     * Set the value of the WORK_ID column.
     * @param workId
     */
    public void setWorkId(java.lang.String workId)
    {
        this.workId = workId;
    }

    /**
     * Return the value of the PROCESS_ID column.
     * @return java.lang.String
     */
    public java.lang.String getProcId()
    {
        return this.procId;
    }

    /**
     * Set the value of the PROCESS_ID column.
     * @param processId
     */
    public void setProcId(java.lang.String procId)
    {
        this.procId = procId;
    }

    /**
     * Return the value of the TXN_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getTxnType()
    {
        return this.txnType;
    }

    /**
     * Set the value of the TXN_TYPE column.
     * @param txnType
     */
    public void setTxnType(java.lang.String txnType)
    {
        this.txnType = txnType;
    }

    /**
     * Return the value of the TRANS_ID column.
     * @return java.lang.String
     */
    public java.lang.String getTransId()
    {
        return this.transId;
    }

    /**
     * Set the value of the TRANS_ID column.
     * @param transId
     */
    public void setTransId(java.lang.String transId)
    {
        this.transId = transId;
    }

    /**
     * Return the value of the SIGN_FIELDS column.
     * @return java.lang.String
     */
    public java.lang.String getSignFields()
    {
        return this.signFields;
    }

    /**
     * Set the value of the SIGN_FIELDS column.
     * @param signFields
     */
    public void setSignFields(java.lang.String signFields)
    {
        this.signFields = signFields;
    }

    /**
     * Return the value of the SIGN_DATA column.
     * @return java.lang.String
     */
    public java.lang.String getSignData()
    {
        return this.signData;
    }

    /**
     * Set the value of the SIGN_DATA column.
     * @param signData
     */
    public void setSignData(java.lang.String signData)
    {
        this.signData = signData;
    }

    /**
     * Return the value of the SIGN_RESULT column.
     * @return java.lang.String
     */
    public java.lang.String getSignResult()
    {
        return this.signResult;
    }

    /**
     * Set the value of the SIGN_RESULT column.
     * @param signResult
     */
    public void setSignResult(java.lang.String signResult)
    {
        this.signResult = signResult;
    }

    /**
     * Return the value of the REMARK column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the ACTION_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getActionTime()
    {
        return this.actionTime;
    }

    /**
     * Set the value of the ACTION_TIME column.
     * @param actionTime
     */
    public void setActionTime(java.util.Date actionTime)
    {
        this.actionTime = actionTime;
    }

    /**
     * Return the value of the ACTION_RESULT column.
     * @return java.lang.String
     */
    public java.lang.String getActionResult()
    {
        return this.actionResult;
    }

    /**
     * Set the value of the ACTION_RESULT column.
     * @param actionResult
     */
    public void setActionResult(java.lang.String actionResult)
    {
        this.actionResult = actionResult;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TxnSignData))
            return false;
        TxnSignData that = (TxnSignData) rhs;
        if (this.getSeqNo() == null || that.getSeqNo() == null)
            return false;
        return (this.getSeqNo().equals(that.getSeqNo()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int seqNoValue = this.getSeqNo() == null ? 0 : this.getSeqNo().hashCode();
            result = result * 37 + seqNoValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
