/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jul 25 15:34:27 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.txn;

import java.io.Serializable;

/**
 * A class that represents a row in the TIME_DEPOSIT table. 
 * You can customize the behavior of this class by editing the class, {@link TimeDeposit()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTimeDeposit 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String transId;

    /** The value of the simple tdType property. */
    private java.lang.String tdType;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple currentAccount property. */
    private java.lang.String currentAccount;
    
    /** The value of the simple currentAccountCcy property. */
    private java.lang.String currentAccountCcy;

    /** The value of the simple tdAccount property. */
    private java.lang.String tdAccount;

    /** The value of the simple currency property. */
    private java.lang.String currency;

    /** The value of the simple principal property. */
    private java.lang.Double principal;

    /** The value of the simple valueDate property. */
    private java.util.Date valueDate;

    /** The value of the simple maturityDate property. */
    private java.util.Date maturityDate;

    /** The value of the simple term property. */
    private java.lang.String term;

    /** The value of the simple productionNo property. */
    private java.lang.String productionNo;

    /** The value of the simple cifNo1 property. */
    private java.lang.String cifNo1;

    /** The value of the simple shortName property. */
    private java.lang.String shortName;

    /** The value of the simple defaultRate property. */
    private java.lang.Double defaultRate;

    /** The value of the simple interest property. */
    private java.lang.Double interest;

    /** The value of the simple penalty property. */
    private java.lang.Double penalty;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple requestTime property. */
    private java.util.Date requestTime;

    /** The value of the simple executeTime property. */
    private java.util.Date executeTime;
    
    /** The value of the simple instCd property. add by linrui 20190424*/
    private java.lang.String instCd;
    /** The value of the simple netCreditAmount property. */
    private java.lang.Double netCreditAmount;
    /**
     * Simple constructor of AbstractTimeDeposit instances.
     */
    public AbstractTimeDeposit()
    {
    }

    /**
     * Constructor of AbstractTimeDeposit instances given a simple primary key.
     * @param transId
     */
    public AbstractTimeDeposit(java.lang.String transId)
    {
        this.setTransId(transId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getTransId()
    {
        return transId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param transId
     */
    public void setTransId(java.lang.String transId)
    {
        this.hashValue = 0;
        this.transId = transId;
    }

    /**
     * Return the value of the TD_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getTdType()
    {
        return this.tdType;
    }

    /**
     * Set the value of the TD_TYPE column.
     * @param tdType
     */
    public void setTdType(java.lang.String tdType)
    {
        this.tdType = tdType;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the CURRENT_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getCurrentAccount()
    {
        return this.currentAccount;
    }

    /**
     * Set the value of the CURRENT_ACCOUNT column.
     * @param currentAccount
     */
    public void setCurrentAccount(java.lang.String currentAccount)
    {
        this.currentAccount = currentAccount;
    }

    /**
     * Return the value of the TD_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getTdAccount()
    {
        return this.tdAccount;
    }

    /**
     * Set the value of the TD_ACCOUNT column.
     * @param tdAccount
     */
    public void setTdAccount(java.lang.String tdAccount)
    {
        this.tdAccount = tdAccount;
    }

    /**
     * Return the value of the CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getCurrency()
    {
        return this.currency;
    }

    /**
     * Set the value of the CURRENCY column.
     * @param currency
     */
    public void setCurrency(java.lang.String currency)
    {
        this.currency = currency;
    }

    /**
     * Return the value of the PRINCIPAL column.
     * @return java.lang.Double
     */
    public java.lang.Double getPrincipal()
    {
        return this.principal;
    }

    /**
     * Set the value of the PRINCIPAL column.
     * @param principal
     */
    public void setPrincipal(java.lang.Double principal)
    {
        this.principal = principal;
    }

    /**
     * Return the value of the MATURITY_DATE column.
     * @return java.util.Date
     */
    public java.util.Date getMaturityDate()
    {
        return this.maturityDate;
    }

    /**
     * Set the value of the MATURITY_DATE column.
     * @param maturityDate
     */
    public void setMaturityDate(java.util.Date maturityDate)
    {
        this.maturityDate = maturityDate;
    }

    /**
     * Return the value of the TERM column.
     * @return java.lang.String
     */
    public java.lang.String getTerm()
    {
        return this.term;
    }

    /**
     * Set the value of the TERM column.
     * @param term
     */
    public void setTerm(java.lang.String term)
    {
        this.term = term;
    }

    /**
     * Return the value of the REMARK column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the REQUEST_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getRequestTime()
    {
        return this.requestTime;
    }

    /**
     * Set the value of the REQUEST_TIME column.
     * @param requestTime
     */
    public void setRequestTime(java.util.Date requestTime)
    {
        this.requestTime = requestTime;
    }

    /**
     * Return the value of the EXECUTE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getExecuteTime()
    {
        return this.executeTime;
    }

    /**
     * Set the value of the EXECUTE_TIME column.
     * @param executeTime
     */
    public void setExecuteTime(java.util.Date executeTime)
    {
        this.executeTime = executeTime;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TimeDeposit))
            return false;
        TimeDeposit that = (TimeDeposit) rhs;
        if (this.getTransId() == null || that.getTransId() == null)
            return false;
        return (this.getTransId().equals(that.getTransId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int transIdValue = this.getTransId() == null ? 0 : this.getTransId().hashCode();
            result = result * 37 + transIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	/**
	 * @return the cifNo1
	 */
	public java.lang.String getCifNo1() {
		return cifNo1;
	}

	/**
	 * @param cifNo1 the cifNo1 to set
	 */
	public void setCifNo1(java.lang.String cifNo1) {
		this.cifNo1 = cifNo1;
	}

	/**
	 * @return the defaultRate
	 */
	public java.lang.Double getDefaultRate() {
		return defaultRate;
	}

	/**
	 * @param defaultRate the defaultRate to set
	 */
	public void setDefaultRate(java.lang.Double defaultRate) {
		this.defaultRate = defaultRate;
	}

	/**
	 * @return the productNo
	 */
	public java.lang.String getProductionNo() {
		return productionNo;
	}

	/**
	 * @param productNo the productNo to set
	 */
	public void setProductionNo(java.lang.String productionNo) {
		this.productionNo = productionNo;
	}

	/**
	 * @return the interest
	 */
	public java.lang.Double getInterest() {
		return interest;
	}

	/**
	 * @param interest the interest to set
	 */
	public void setInterest(java.lang.Double interest) {
		this.interest = interest;
	}

	/**
	 * @return the penalty
	 */
	public java.lang.Double getPenalty() {
		return penalty;
	}

	/**
	 * @param penalty the penalty to set
	 */
	public void setPenalty(java.lang.Double penalty) {
		this.penalty = penalty;
	}

	/**
	 * @return the shortName
	 */
	public java.lang.String getShortName() {
		return shortName;
	}

	/**
	 * @param shortName the shortName to set
	 */
	public void setShortName(java.lang.String shortName) {
		this.shortName = shortName;
	}

	/**
	 * @return the valueDate
	 */
	public java.util.Date getValueDate() {
		return valueDate;
	}

	/**
	 * @param valueDate the valueDate to set
	 */
	public void setValueDate(java.util.Date valueDate) {
		this.valueDate = valueDate;
	}
	
	/**
	 * @param return the currentAccountCcy 
	 */
	public java.lang.String getCurrentAccountCcy() {
		return currentAccountCcy;
	}
	
	/**
	 * @param valueDate the currentAccountCcy to set
	 */
	public void setCurrentAccountCcy(java.lang.String currentAccountCcy) {
		this.currentAccountCcy = currentAccountCcy;
	}
	
	/**
     * Return the value of the instCd column.
     * @return java.lang.String
     */
    public java.lang.String getInstCd()
    {
        return this.instCd;
    }

    /**
     * Set the value of the instCd column.
     * @param authStatus
     */
    public void setInstCd(java.lang.String instCd)
    {
        this.instCd = instCd;
    }
    /**
     * Set the value of the netCreditAmount column.
     * @param authStatus
     */
	public java.lang.Double getNetCreditAmount() {
		return netCreditAmount;
	}

	public void setNetCreditAmount(java.lang.Double netCreditAmount) {
		this.netCreditAmount = netCreditAmount;
	}
	
	
}
