//package app.cib.util.smsclient.log;
//
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceFeature;
//import javax.xml.ws.Service;
//
//import org.apache.cxf.feature.Features;
//
///**
// * This class was generated by Apache CXF 2.6.4
// * 2014-07-24T16:20:19.277+08:00
// * Generated source version: 2.6.4
// * 
// */
//@WebServiceClient(name = "LogInterAgentService", 
//                  wsdlLocation = "d:/log.wsdl",
//                  targetNamespace = "http://logservice.bank.com/")
//@Features(features = "org.apache.cxf.feature.LoggingFeature")
//public class LogInterAgentService extends Service {
//
//    public final static URL WSDL_LOCATION;
//
//    public final static QName SERVICE = new QName("http://logservice.bank.com/", "LogInterAgentService");
//    public final static QName LogInterAgentPort = new QName("http://logservice.bank.com/", "LogInterAgentPort");
//    static {
//        URL url = LogInterAgentService.class.getResource("d:/log.wsdl");
//        if (url == null) {
//            java.util.logging.Logger.getLogger(LogInterAgentService.class.getName())
//                .log(java.util.logging.Level.INFO, 
//                     "Can not initialize the default wsdl from {0}", "d:/log.wsdl");
//        }       
//        WSDL_LOCATION = url;
//    }
//
//    public LogInterAgentService(URL wsdlLocation) {
//        super(wsdlLocation, SERVICE);
//    }
//
//    public LogInterAgentService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public LogInterAgentService() {
//        super(WSDL_LOCATION, SERVICE);
//    }
//    
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    /*public LogInterAgentService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }*/
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//   /* public LogInterAgentService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }*/
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//   /* public LogInterAgentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }*/
//
//    /**
//     *
//     * @return
//     *     returns LogInterAgent
//     */
//    @WebEndpoint(name = "LogInterAgentPort")
//    public LogInterAgent getLogInterAgentPort() {
//        return super.getPort(LogInterAgentPort, LogInterAgent.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns LogInterAgent
//     */
//    @WebEndpoint(name = "LogInterAgentPort")
//    public LogInterAgent getLogInterAgentPort(WebServiceFeature... features) {
//        return super.getPort(LogInterAgentPort, LogInterAgent.class, features);
//    }
//
//}
