package app.cib.util.smsclient.log;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2014-07-24T16:20:19.268+08:00
 * Generated source version: 2.6.4
 * 
 */
@WebService(targetNamespace = "http://logservice.bank.com/", name = "LogInterAgent")
@XmlSeeAlso({ObjectFactory.class})
public interface LogInterAgent {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logInfo", targetNamespace = "http://logservice.bank.com/", className = "app.cib.util.smsclient.log.LogInfo")
    @WebMethod
    @ResponseWrapper(localName = "logInfoResponse", targetNamespace = "http://logservice.bank.com/", className = "app.cib.util.smsclient.log.LogInfoResponse")
    public app.cib.util.smsclient.log.LogResponse logInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        app.cib.util.smsclient.log.LogRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logSms", targetNamespace = "http://logservice.bank.com/", className = "app.cib.util.smsclient.log.LogSms")
    @WebMethod
    @ResponseWrapper(localName = "logSmsResponse", targetNamespace = "http://logservice.bank.com/", className = "app.cib.util.smsclient.log.LogSmsResponse")
    public app.cib.util.smsclient.log.LogResponse logSms(
        @WebParam(name = "arg0", targetNamespace = "")
        app.cib.util.smsclient.log.LogSmsRequest arg0
    );
}
