//
//package app.cib.util.smsclient.log;
//
///**
// * Please modify this class to meet your needs
// * This class is not complete
// */
//
//import java.io.File;
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;
//
///**
// * This class was generated by Apache CXF 2.6.4
// * 2014-07-24T16:20:19.126+08:00
// * Generated source version: 2.6.4
// * 
// */
//public final class LogInterAgent_LogInterAgentPort_Client {
//
//    private static final QName SERVICE_NAME = new QName("http://logservice.bank.com/", "LogInterAgentService");
//
//    private LogInterAgent_LogInterAgentPort_Client() {
//    }
//
//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = LogInterAgentService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        LogInterAgentService ss = new LogInterAgentService(wsdlURL, SERVICE_NAME);
//        LogInterAgent port = ss.getLogInterAgentPort();  
//        
//        {
//        System.out.println("Invoking logInfo...");
//        app.cib.util.smsclient.log.LogRequest _logInfo_arg0 = null;
//        app.cib.util.smsclient.log.LogResponse _logInfo__return = port.logInfo(_logInfo_arg0);
//        System.out.println("logInfo.result=" + _logInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking logSms...");
//        app.cib.util.smsclient.log.LogSmsRequest _logSms_arg0 = null;
//        app.cib.util.smsclient.log.LogResponse _logSms__return = port.logSms(_logSms_arg0);
//        System.out.println("logSms.result=" + _logSms__return);
//
//
//        }
//
//        System.exit(0);
//    }
//
//}
