//
//package app.cib.util.smsclient.sms;
//
///**
// * Please modify this class to meet your needs
// * This class is not complete
// */
//
//import java.io.File;
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;
//
///**
// * This class was generated by Apache CXF 2.6.4
// * 2014-07-24T16:05:41.602+08:00
// * Generated source version: 2.6.4
// * 
// */
//public final class SmsInterAgent_SmsInterAgentPort_Client {
//
//    private static final QName SERVICE_NAME = new QName("http://smsservice.bank.com/", "SmsInterAgentService");
//
//    private SmsInterAgent_SmsInterAgentPort_Client() {
//    }
//
//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = SmsInterAgentService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        SmsInterAgentService ss = new SmsInterAgentService(wsdlURL, SERVICE_NAME);
//        SmsInterAgent port = ss.getSmsInterAgentPort();  
//        
//        {
//        System.out.println("Invoking sendSms...");
//        app.cib.util.smsclient.sms.SmsRequest _sendSms_arg0 = null;
//        app.cib.util.smsclient.sms.SmsResponse _sendSms__return = port.sendSms(_sendSms_arg0);
//        System.out.println("sendSms.result=" + _sendSms__return);
//
//
//        }
//
//        System.exit(0);
//    }
//
//}
