//package app.cib.util.smsclient.sms;
//
//import java.net.URL;
//
//import javax.xml.namespace.QName;
//import javax.xml.ws.Service;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceFeature;
//
//import org.apache.cxf.feature.Features;
//
///**
// * This class was generated by Apache CXF 2.6.4
// * 2014-07-24T16:05:42.087+08:00
// * Generated source version: 2.6.4
// * 
// */
//@WebServiceClient(name = "SmsInterAgentService", 
//                  wsdlLocation = "d:/smsinter.wsdl",
//                  targetNamespace = "http://smsservice.bank.com/") 
//@Features(features = "org.apache.cxf.feature.LoggingFeature")
//public class SmsInterAgentService extends Service {
//
//    public final static URL WSDL_LOCATION;
//
//    public final static QName SERVICE = new QName("http://smsservice.bank.com/", "SmsInterAgentService");
//    public final static QName SmsInterAgentPort = new QName("http://smsservice.bank.com/", "SmsInterAgentPort");
//    static {
//        URL url = SmsInterAgentService.class.getResource("d:/smsinter.wsdl");
//        if (url == null) {
//            java.util.logging.Logger.getLogger(SmsInterAgentService.class.getName())
//                .log(java.util.logging.Level.INFO, 
//                     "Can not initialize the default wsdl from {0}", "d:/smsinter.wsdl");
//        }       
//        WSDL_LOCATION = url;
//    }
//
//    public SmsInterAgentService(URL wsdlLocation) {
//        super(wsdlLocation, SERVICE);
//    }
//
//    public SmsInterAgentService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public SmsInterAgentService() {
//        super(WSDL_LOCATION, SERVICE);
//    }
//    
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//  /*  public SmsInterAgentService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }*/
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    /*public SmsInterAgentService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }*/
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    /*public SmsInterAgentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }*/
//
//    /**
//     *
//     * @return
//     *     returns SmsInterAgent
//     */
//    @WebEndpoint(name = "SmsInterAgentPort")
//    public SmsInterAgent getSmsInterAgentPort() {
//        return super.getPort(SmsInterAgentPort, SmsInterAgent.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns SmsInterAgent
//     */
//    @WebEndpoint(name = "SmsInterAgentPort")
//    public SmsInterAgent getSmsInterAgentPort(WebServiceFeature... features) {
//        return super.getPort(SmsInterAgentPort, SmsInterAgent.class, features);
//    }
//
//}
