package app.cib.util.smsclient.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.4
 * 2014-07-24T16:05:42.048+08:00
 * Generated source version: 2.6.4
 * 
 */
@WebService(targetNamespace = "http://smsservice.bank.com/", name = "SmsInterAgent")
@XmlSeeAlso({ObjectFactory.class})
public interface SmsInterAgent {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://smsservice.bank.com/", className = "app.cib.util.smsclient.sms.SendSms")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://smsservice.bank.com/", className = "app.cib.util.smsclient.sms.SendSmsResponse")
    public app.cib.util.smsclient.sms.SmsResponse sendSms(
        @WebParam(name = "arg0", targetNamespace = "")
        app.cib.util.smsclient.sms.SmsRequest arg0
    );
}
