/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sun Aug 06 15:30:12 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.sys;

import java.io.Serializable;

/**
 * A class that represents a row in the TELLER_SEQUENCE table. 
 * You can customize the behavior of this class by editing the class, {@link TellerSequence()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTellerSequence 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String seqNo;

    /** The value of the simple teller property. */
    private java.lang.String teller;

    /** The value of the simple currentSequence property. */
    private java.lang.Integer currentSequence;

    /** The value of the simple effectiveDate property. */
    private java.lang.String effectiveDate;

    /**
     * Simple constructor of AbstractTellerSequence instances.
     */
    public AbstractTellerSequence()
    {
    }

    /**
     * Constructor of AbstractTellerSequence instances given a simple primary key.
     * @param seqNo
     */
    public AbstractTellerSequence(java.lang.String seqNo)
    {
        this.setSeqNo(seqNo);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getSeqNo()
    {
        return seqNo;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param seqNo
     */
    public void setSeqNo(java.lang.String seqNo)
    {
        this.hashValue = 0;
        this.seqNo = seqNo;
    }

    /**
     * Return the value of the TELLER column.
     * @return java.lang.String
     */
    public java.lang.String getTeller()
    {
        return this.teller;
    }

    /**
     * Set the value of the TELLER column.
     * @param teller
     */
    public void setTeller(java.lang.String teller)
    {
        this.teller = teller;
    }

    /**
     * Return the value of the CURRENT_SEQUENCE column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getCurrentSequence()
    {
        return this.currentSequence;
    }

    /**
     * Set the value of the CURRENT_SEQUENCE column.
     * @param currentSequence
     */
    public void setCurrentSequence(java.lang.Integer currentSequence)
    {
        this.currentSequence = currentSequence;
    }

    /**
     * Return the value of the EFFECTIVE_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getEffectiveDate()
    {
        return this.effectiveDate;
    }

    /**
     * Set the value of the EFFECTIVE_DATE column.
     * @param effectiveDate
     */
    public void setEffectiveDate(java.lang.String effectiveDate)
    {
        this.effectiveDate = effectiveDate;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TellerSequence))
            return false;
        TellerSequence that = (TellerSequence) rhs;
        if (this.getSeqNo() == null || that.getSeqNo() == null)
            return false;
        return (this.getSeqNo().equals(that.getSeqNo()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int seqNoValue = this.getSeqNo() == null ? 0 : this.getSeqNo().hashCode();
            result = result * 37 + seqNoValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
