/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Mar 01 14:32:51 CST 2007 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.sys;

import java.io.Serializable;

/**
 * A class that represents a row in the APPROVE_RULE table. 
 * You can customize the behavior of this class by editing the class, {@link ApproveRule()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractApproveRule 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String ruleId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple prefId property. */
    private java.lang.String prefId;

    /** The value of the simple txnType property. */
    private java.lang.String txnType;

    /** The value of the simple currency property. */
    private java.lang.String currency;

    /** The value of the simple ruleType property. */
    private java.lang.String ruleType;

    /** The value of the simple singleLevel property. */
    private java.lang.String singleLevel;

    /** The value of the simple fromAmount property. */
    private java.lang.Double fromAmount;

    /** The value of the simple toAmount property. */
    private java.lang.Double toAmount;

    /** The value of the simple levelA property. */
    private java.lang.Integer levelA;

    /** The value of the simple levelD property. */
    private java.lang.Integer levelD;

    /** The value of the simple levelC property. */
    private java.lang.Integer levelC;

    /** The value of the simple levelB property. */
    private java.lang.Integer levelB;

    /** The value of the simple levelE property. */
    private java.lang.Integer levelE;

    /** The value of the simple levelF property. */
    private java.lang.Integer levelF;

    /** The value of the simple levelG property. */
    private java.lang.Integer levelG;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple lastUpdateTime property. */
    private java.util.Date lastUpdateTime;

    /** The value of the simple requester property. */
    private java.lang.String requester;

    /** The value of the simple afterModifyId property. */
    private java.lang.String afterModifyId;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /**
     * Simple constructor of AbstractApproveRule instances.
     */
    public AbstractApproveRule()
    {
    }

    /**
     * Constructor of AbstractApproveRule instances given a simple primary key.
     * @param ruleId
     */
    public AbstractApproveRule(java.lang.String ruleId)
    {
        this.setRuleId(ruleId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getRuleId()
    {
        return ruleId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param ruleId
     */
    public void setRuleId(java.lang.String ruleId)
    {
        this.hashValue = 0;
        this.ruleId = ruleId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the PREF_ID column.
     * @return java.lang.String
     */
    public java.lang.String getPrefId()
    {
        return this.prefId;
    }

    /**
     * Set the value of the PREF_ID column.
     * @param prefId
     */
    public void setPrefId(java.lang.String prefId)
    {
        this.prefId = prefId;
    }

    /**
     * Return the value of the TXN_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getTxnType()
    {
        return this.txnType;
    }

    /**
     * Set the value of the TXN_TYPE column.
     * @param txnType
     */
    public void setTxnType(java.lang.String txnType)
    {
        this.txnType = txnType;
    }

    /**
     * Return the value of the CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getCurrency()
    {
        return this.currency;
    }

    /**
     * Set the value of the CURRENCY column.
     * @param currency
     */
    public void setCurrency(java.lang.String currency)
    {
        this.currency = currency;
    }

    /**
     * Return the value of the RULE_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getRuleType()
    {
        return this.ruleType;
    }

    /**
     * Set the value of the RULE_TYPE column.
     * @param ruleType
     */
    public void setRuleType(java.lang.String ruleType)
    {
        this.ruleType = ruleType;
    }

    /**
     * Return the value of the SINGLE_LEVEL column.
     * @return java.lang.String
     */
    public java.lang.String getSingleLevel()
    {
        return this.singleLevel;
    }

    /**
     * Set the value of the SINGLE_LEVEL column.
     * @param singleLevel
     */
    public void setSingleLevel(java.lang.String singleLevel)
    {
        this.singleLevel = singleLevel;
    }

    /**
     * Return the value of the FROM_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getFromAmount()
    {
        return this.fromAmount;
    }

    /**
     * Set the value of the FROM_AMOUNT column.
     * @param fromAmount
     */
    public void setFromAmount(java.lang.Double fromAmount)
    {
        this.fromAmount = fromAmount;
    }

    /**
     * Return the value of the TO_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getToAmount()
    {
        return this.toAmount;
    }

    /**
     * Set the value of the TO_AMOUNT column.
     * @param toAmount
     */
    public void setToAmount(java.lang.Double toAmount)
    {
        this.toAmount = toAmount;
    }

    /**
     * Return the value of the LEVEL_A column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelA()
    {
        return this.levelA;
    }

    /**
     * Set the value of the LEVEL_A column.
     * @param levelA
     */
    public void setLevelA(java.lang.Integer levelA)
    {
        this.levelA = levelA;
    }

    /**
     * Return the value of the LEVEL_D column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelD()
    {
        return this.levelD;
    }

    /**
     * Set the value of the LEVEL_D column.
     * @param levelD
     */
    public void setLevelD(java.lang.Integer levelD)
    {
        this.levelD = levelD;
    }

    /**
     * Return the value of the LEVEL_C column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelC()
    {
        return this.levelC;
    }

    /**
     * Set the value of the LEVEL_C column.
     * @param levelC
     */
    public void setLevelC(java.lang.Integer levelC)
    {
        this.levelC = levelC;
    }

    /**
     * Return the value of the LEVEL_B column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelB()
    {
        return this.levelB;
    }

    /**
     * Set the value of the LEVEL_B column.
     * @param levelB
     */
    public void setLevelB(java.lang.Integer levelB)
    {
        this.levelB = levelB;
    }

    /**
     * Return the value of the LEVEL_E column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelE()
    {
        return this.levelE;
    }

    /**
     * Set the value of the LEVEL_E column.
     * @param levelE
     */
    public void setLevelE(java.lang.Integer levelE)
    {
        this.levelE = levelE;
    }

    /**
     * Return the value of the LEVEL_F column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelF()
    {
        return this.levelF;
    }

    /**
     * Set the value of the LEVEL_F column.
     * @param levelF
     */
    public void setLevelF(java.lang.Integer levelF)
    {
        this.levelF = levelF;
    }

    /**
     * Return the value of the LEVEL_G column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelG()
    {
        return this.levelG;
    }

    /**
     * Set the value of the LEVEL_G column.
     * @param levelG
     */
    public void setLevelG(java.lang.Integer levelG)
    {
        this.levelG = levelG;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the LAST_UPDATE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getLastUpdateTime()
    {
        return this.lastUpdateTime;
    }

    /**
     * Set the value of the LAST_UPDATE_TIME column.
     * @param lastUpdateTime
     */
    public void setLastUpdateTime(java.util.Date lastUpdateTime)
    {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * Return the value of the REQUESTER column.
     * @return java.lang.String
     */
    public java.lang.String getRequester()
    {
        return this.requester;
    }

    /**
     * Set the value of the REQUESTER column.
     * @param requester
     */
    public void setRequester(java.lang.String requester)
    {
        this.requester = requester;
    }

    /**
     * Return the value of the AFTER_MODIFY_ID column.
     * @return java.lang.String
     */
    public java.lang.String getAfterModifyId()
    {
        return this.afterModifyId;
    }

    /**
     * Set the value of the AFTER_MODIFY_ID column.
     * @param afterModifyId
     */
    public void setAfterModifyId(java.lang.String afterModifyId)
    {
        this.afterModifyId = afterModifyId;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof ApproveRule))
            return false;
        ApproveRule that = (ApproveRule) rhs;
        if (this.getRuleId() == null || that.getRuleId() == null)
            return false;
        return (this.getRuleId().equals(that.getRuleId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int ruleIdValue = this.getRuleId() == null ? 0 : this.getRuleId().hashCode();
            result = result * 37 + ruleIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
