/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Sep 26 18:57:29 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.sys;

import java.io.Serializable;

/**
 * A class that represents a row in the CORP_PERMISSION table. 
 * You can customize the behavior of this class by editing the class, {@link CorpPermission()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCorpPermission 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String permissionId;

    /** The value of the simple roleId property. */
    private java.lang.String roleId;

    /** The value of the simple groupId property. */
    private java.lang.String groupId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple permissionResource property. */
    private java.lang.String permissionResource;

    /** The value of the simple permissionType property. */
    private java.lang.String permissionType;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple version property. */
    private java.lang.Integer version;

    /** The value of the simple lastUpdateTime property. */
    private java.util.Date lastUpdateTime;

    /** The value of the simple requester property. */
    private java.lang.String requester;

    /**
     * Simple constructor of AbstractCorpPermission instances.
     */
    public AbstractCorpPermission()
    {
    }

    /**
     * Constructor of AbstractCorpPermission instances given a simple primary key.
     * @param permissionId
     */
    public AbstractCorpPermission(java.lang.String permissionId)
    {
        this.setPermissionId(permissionId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getPermissionId()
    {
        return permissionId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param permissionId
     */
    public void setPermissionId(java.lang.String permissionId)
    {
        this.hashValue = 0;
        this.permissionId = permissionId;
    }

    /**
     * Return the value of the ROLE_ID column.
     * @return java.lang.String
     */
    public java.lang.String getRoleId()
    {
        return this.roleId;
    }

    /**
     * Set the value of the ROLE_ID column.
     * @param roleId
     */
    public void setRoleId(java.lang.String roleId)
    {
        this.roleId = roleId;
    }

    /**
     * Return the value of the GROUP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getGroupId()
    {
        return this.groupId;
    }

    /**
     * Set the value of the GROUP_ID column.
     * @param groupId
     */
    public void setGroupId(java.lang.String groupId)
    {
        this.groupId = groupId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the PERMISSION_RESOURCE column.
     * @return java.lang.String
     */
    public java.lang.String getPermissionResource()
    {
        return this.permissionResource;
    }

    /**
     * Set the value of the PERMISSION_RESOURCE column.
     * @param permissionResource
     */
    public void setPermissionResource(java.lang.String permissionResource)
    {
        this.permissionResource = permissionResource;
    }

    /**
     * Return the value of the PERMISSION_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getPermissionType()
    {
        return this.permissionType;
    }

    /**
     * Set the value of the PERMISSION_TYPE column.
     * @param permissionType
     */
    public void setPermissionType(java.lang.String permissionType)
    {
        this.permissionType = permissionType;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the VERSION column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getVersion()
    {
        return this.version;
    }

    /**
     * Set the value of the VERSION column.
     * @param version
     */
    public void setVersion(java.lang.Integer version)
    {
        this.version = version;
    }

    /**
     * Return the value of the LAST_UPDATE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getLastUpdateTime()
    {
        return this.lastUpdateTime;
    }

    /**
     * Set the value of the LAST_UPDATE_TIME column.
     * @param lastUpdateTime
     */
    public void setLastUpdateTime(java.util.Date lastUpdateTime)
    {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * Return the value of the REQUESTER column.
     * @return java.lang.String
     */
    public java.lang.String getRequester()
    {
        return this.requester;
    }

    /**
     * Set the value of the REQUESTER column.
     * @param requester
     */
    public void setRequester(java.lang.String requester)
    {
        this.requester = requester;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CorpPermission))
            return false;
        CorpPermission that = (CorpPermission) rhs;
        if (this.getPermissionId() == null || that.getPermissionId() == null)
            return false;
        return (this.getPermissionId().equals(that.getPermissionId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int permissionIdValue = this.getPermissionId() == null ? 0 : this.getPermissionId().hashCode();
            result = result * 37 + permissionIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
