/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Sep 26 18:45:00 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.sys;

import java.io.Serializable;

/**
 * A class that represents a row in the USER_GROUP_HIS table. 
 * You can customize the behavior of this class by editing the class, {@link UserGroupHis()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUserGroupHis 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String seqNo;

    /** The value of the simple groupId property. */
    private java.lang.String groupId;

    /** The value of the simple roleId property. */
    private java.lang.String roleId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple groupName property. */
    private java.lang.String groupName;

    /** The value of the simple groupDesc property. */
    private java.lang.String groupDesc;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple version property. */
    private java.lang.Integer version;

    /** The value of the simple lastUpdateTime property. */
    private java.util.Date lastUpdateTime;

    /** The value of the simple requester property. */
    private java.lang.String requester;

    /**
     * Simple constructor of AbstractUserGroupHis instances.
     */
    public AbstractUserGroupHis()
    {
    }

    /**
     * Constructor of AbstractUserGroupHis instances given a simple primary key.
     * @param seqNo
     */
    public AbstractUserGroupHis(java.lang.String seqNo)
    {
        this.setSeqNo(seqNo);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getSeqNo()
    {
        return seqNo;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param seqNo
     */
    public void setSeqNo(java.lang.String seqNo)
    {
        this.hashValue = 0;
        this.seqNo = seqNo;
    }

    /**
     * Return the value of the GROUP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getGroupId()
    {
        return this.groupId;
    }

    /**
     * Set the value of the GROUP_ID column.
     * @param groupId
     */
    public void setGroupId(java.lang.String groupId)
    {
        this.groupId = groupId;
    }

    /**
     * Return the value of the ROLE_ID column.
     * @return java.lang.String
     */
    public java.lang.String getRoleId()
    {
        return this.roleId;
    }

    /**
     * Set the value of the ROLE_ID column.
     * @param roleId
     */
    public void setRoleId(java.lang.String roleId)
    {
        this.roleId = roleId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the GROUP_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getGroupName()
    {
        return this.groupName;
    }

    /**
     * Set the value of the GROUP_NAME column.
     * @param groupName
     */
    public void setGroupName(java.lang.String groupName)
    {
        this.groupName = groupName;
    }

    /**
     * Return the value of the GROUP_DESC column.
     * @return java.lang.String
     */
    public java.lang.String getGroupDesc()
    {
        return this.groupDesc;
    }

    /**
     * Set the value of the GROUP_DESC column.
     * @param groupDesc
     */
    public void setGroupDesc(java.lang.String groupDesc)
    {
        this.groupDesc = groupDesc;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the VERSION column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getVersion()
    {
        return this.version;
    }

    /**
     * Set the value of the VERSION column.
     * @param version
     */
    public void setVersion(java.lang.Integer version)
    {
        this.version = version;
    }

    /**
     * Return the value of the LAST_UPDATE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getLastUpdateTime()
    {
        return this.lastUpdateTime;
    }

    /**
     * Set the value of the LAST_UPDATE_TIME column.
     * @param lastUpdateTime
     */
    public void setLastUpdateTime(java.util.Date lastUpdateTime)
    {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * Return the value of the REQUESTER column.
     * @return java.lang.String
     */
    public java.lang.String getRequester()
    {
        return this.requester;
    }

    /**
     * Set the value of the REQUESTER column.
     * @param requester
     */
    public void setRequester(java.lang.String requester)
    {
        this.requester = requester;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof UserGroupHis))
            return false;
        UserGroupHis that = (UserGroupHis) rhs;
        if (this.getSeqNo() == null || that.getSeqNo() == null)
            return false;
        return (this.getSeqNo().equals(that.getSeqNo()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int seqNoValue = this.getSeqNo() == null ? 0 : this.getSeqNo().hashCode();
            result = result * 37 + seqNoValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
