/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Mar 01 14:31:45 CST 2007 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.sys;

import java.io.Serializable;

/**
 * A class that represents a row in the CORP_USER table. 
 * You can customize the behavior of this class by editing the class, {@link CorpUser()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCorpUser 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;
    
    private CorpUserId id ;

    /** The composite primary key value. */
    private java.lang.String userId;

    /** The value of the simple prefId property. */
    private java.lang.String prefId;

    /** The value of the simple loginId property. */
    private java.lang.String loginId;

    /** The value of the simple userPassword property. */
    private java.lang.String userPassword;

    /** The value of the simple securityCode property. */
    private java.lang.String securityCode;

    /** The value of the simple userName property. */
    private java.lang.String userName;

    /** The value of the simple roleId property. */
    private java.lang.String roleId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple groupId property. */
    private java.lang.String groupId;

    /** The value of the simple authLevel property. */
    private java.lang.String authLevel;

    /** The value of the simple idType property. */
    private java.lang.String idType;

    /** The value of the simple idNo property. */
    private java.lang.String idNo;

    /** The value of the simple email property. */
    private java.lang.String email;

    /** The value of the simple userDesc property. */
    private java.lang.String userDesc;

    /** The value of the simple certInfo1 property. */
    private java.lang.String certInfo1;

    /** The value of the simple certInfo2 property. */
    private java.lang.String certInfo2;

    /** The value of the simple certInfo3 property. */
    private java.lang.String certInfo3;

    /** The value of the simple limit1 property. */
    private java.lang.Double limit1;

    /** The value of the simple limit2 property. */
    private java.lang.Double limit2;

    /** The value of the simple limit3 property. */
    private java.lang.Double limit3;

    /** The value of the simple limit4 property. */
    private java.lang.Double limit4;

    /** The value of the simple limit5 property. */
    private java.lang.Double limit5;

    /** The value of the simple limit6 property. */
    private java.lang.Double limit6;

    /** The value of the simple limit7 property. */
    private java.lang.Double limit7;

    /** The value of the simple limit8 property. */
    private java.lang.Double limit8;

    /** The value of the simple limit9 property. */
    private java.lang.Double limit9;

    /** The value of the simple limit10 property. */
    private java.lang.Double limit10;

    /** The value of the simple loginStatus property. */
    private java.lang.String loginStatus;

    /** The value of the simple loginTimes property. */
    private java.lang.Integer loginTimes;

    /** The value of the simple loginFailTimes property. */
    private java.lang.Integer loginFailTimes;

    /** The value of the simple currLoginIp property. */
    private java.lang.String currLoginIp;

    /** The value of the simple currLoginTime property. */
    private java.util.Date currLoginTime;

    /** The value of the simple prevLoginIp property. */
    private java.lang.String prevLoginIp;

    /** The value of the simple prevLoginTime property. */
    private java.util.Date prevLoginTime;

    /** The value of the simple pervLoginStatus property. */
    private java.lang.String pervLoginStatus;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple blockReason property. */
    private java.lang.String blockReason;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple version property. */
    private java.lang.Integer version;

    /** The value of the simple lastUpdateTime property. */
    private java.util.Date lastUpdateTime;

    /** The value of the simple requester property. */
    private java.lang.String requester;

    /** The value of the simple fullName property. */
    private java.lang.String fullName;

    /** The value of the simple title property. */
    private java.lang.String title;

    /** The value of the simple gender property. */
    private java.lang.String gender;

    /** The value of the simple idIssueDate property. */
    private java.util.Date idIssueDate;

    /** The value of the simple idIssuer property. */
    private java.lang.String idIssuer;

    /** The value of the simple telephone property. */
    private java.lang.String telephone;

    /** The value of the simple mobile property. */
    private java.lang.String mobile;

    /** The value of the simple faxNo property. */
    private java.lang.String faxNo;

    /** The value of the simple viewAllTransFlag property. */
    private java.lang.String viewAllTransFlag;

    /** The value of the simple financialControllerFlag property. */
    private java.lang.String financialControllerFlag;
    
    private java.lang.String merchantType;
    private java.lang.String certCardType;
    
//    <!-- modify by long_zg 2014-04-03 for CR204 Apply OTP to BOB begin -->
    private java.lang.String mobileCountryCode ;
    private java.lang.String mobileAreaCode ;
    
    
//    <!-- modify by long_zg 2014-04-03 for CR204 Apply OTP to BOB end -->
    /**
     * Simple constructor of AbstractCorpUser instances.
     */
    public AbstractCorpUser()
    {
    	if(null==id){
    		id = new CorpUserId() ;
    	}
    }

    /**
     * Constructor of AbstractCorpUser instances given a simple primary key.
     * @param userId
     */
    public AbstractCorpUser(java.lang.String userId)
    {
    	if(null==id){
    		id = new CorpUserId() ;
    	}
        this.setUserId(userId);
        
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
//        return userId;
        return id.getUserId();
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.hashValue = 0;
//        this.userId = userId;
        this.userId = userId;
        this.id.setUserId(userId) ;
    }

    /**
     * Return the value of the PREF_ID column.
     * @return java.lang.String
     */
    public java.lang.String getPrefId()
    {
        return this.prefId;
    }

    /**
     * Set the value of the PREF_ID column.
     * @param prefId
     */
    public void setPrefId(java.lang.String prefId)
    {
        this.prefId = prefId;
    }

    /**
     * Return the value of the LOGIN_ID column.
     * @return java.lang.String
     */
    public java.lang.String getLoginId()
    {
        return this.loginId;
    }

    /**
     * Set the value of the LOGIN_ID column.
     * @param loginId
     */
    public void setLoginId(java.lang.String loginId)
    {
        this.loginId = loginId;
    }

    /**
     * Return the value of the USER_PASSWORD column.
     * @return java.lang.String
     */
    public java.lang.String getUserPassword()
    {
        return this.userPassword;
    }

    /**
     * Set the value of the USER_PASSWORD column.
     * @param userPassword
     */
    public void setUserPassword(java.lang.String userPassword)
    {
        this.userPassword = userPassword;
    }

    /**
     * Return the value of the USER_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getUserName()
    {
        return this.userName;
    }

    /**
     * Set the value of the USER_NAME column.
     * @param userName
     */
    public void setUserName(java.lang.String userName)
    {
        this.userName = userName;
    }

    /**
     * Return the value of the ROLE_ID column.
     * @return java.lang.String
     */
    public java.lang.String getRoleId()
    {
        return this.roleId;
    }

    /**
     * Set the value of the ROLE_ID column.
     * @param roleId
     */
    public void setRoleId(java.lang.String roleId)
    {
        this.roleId = roleId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
//        return this.corpId;
        return this.id.getCorpId();
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
        this.id.setCorpId(corpId) ;
    }

    /**
     * Return the value of the GROUP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getGroupId()
    {
        return this.groupId;
    }

    /**
     * Set the value of the GROUP_ID column.
     * @param groupId
     */
    public void setGroupId(java.lang.String groupId)
    {
        this.groupId = groupId;
    }

    /**
     * Return the value of the AUTH_LEVEL column.
     * @return java.lang.String
     */
    public java.lang.String getAuthLevel()
    {
        return this.authLevel;
    }

    /**
     * Set the value of the AUTH_LEVEL column.
     * @param authLevel
     */
    public void setAuthLevel(java.lang.String authLevel)
    {
        this.authLevel = authLevel;
    }

    /**
     * Return the value of the ID_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getIdType()
    {
        return this.idType;
    }

    /**
     * Set the value of the ID_TYPE column.
     * @param idType
     */
    public void setIdType(java.lang.String idType)
    {
        this.idType = idType;
    }

    /**
     * Return the value of the ID_NO column.
     * @return java.lang.String
     */
    public java.lang.String getIdNo()
    {
        return this.idNo;
    }

    /**
     * Set the value of the ID_NO column.
     * @param idNo
     */
    public void setIdNo(java.lang.String idNo)
    {
        this.idNo = idNo;
    }

    /**
     * Return the value of the EMAIL column.
     * @return java.lang.String
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    /**
     * Set the value of the EMAIL column.
     * @param email
     */
    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    /**
     * Return the value of the USER_DESC column.
     * @return java.lang.String
     */
    public java.lang.String getUserDesc()
    {
        return this.userDesc;
    }

    /**
     * Set the value of the USER_DESC column.
     * @param userDesc
     */
    public void setUserDesc(java.lang.String userDesc)
    {
        this.userDesc = userDesc;
    }

    /**
     * Return the value of the CERT_INFO1 column.
     * @return java.lang.String
     */
    public java.lang.String getCertInfo1()
    {
        return this.certInfo1;
    }

    /**
     * Set the value of the CERT_INFO1 column.
     * @param certInfo1
     */
    public void setCertInfo1(java.lang.String certInfo1)
    {
        this.certInfo1 = certInfo1;
    }

    /**
     * Return the value of the CERT_INFO2 column.
     * @return java.lang.String
     */
    public java.lang.String getCertInfo2()
    {
        return this.certInfo2;
    }

    /**
     * Set the value of the CERT_INFO2 column.
     * @param certInfo2
     */
    public void setCertInfo2(java.lang.String certInfo2)
    {
        this.certInfo2 = certInfo2;
    }

    /**
     * Return the value of the CERT_INFO3 column.
     * @return java.lang.String
     */
    public java.lang.String getCertInfo3()
    {
        return this.certInfo3;
    }

    /**
     * Set the value of the CERT_INFO3 column.
     * @param certInfo3
     */
    public void setCertInfo3(java.lang.String certInfo3)
    {
        this.certInfo3 = certInfo3;
    }

    /**
     * Return the value of the LIMIT1 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit1()
    {
        return this.limit1;
    }

    /**
     * Set the value of the LIMIT1 column.
     * @param limit1
     */
    public void setLimit1(java.lang.Double limit1)
    {
        this.limit1 = limit1;
    }

    /**
     * Return the value of the LIMIT2 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit2()
    {
        return this.limit2;
    }

    /**
     * Set the value of the LIMIT2 column.
     * @param limit2
     */
    public void setLimit2(java.lang.Double limit2)
    {
        this.limit2 = limit2;
    }

    /**
     * Return the value of the LIMIT3 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit3()
    {
        return this.limit3;
    }

    /**
     * Set the value of the LIMIT3 column.
     * @param limit3
     */
    public void setLimit3(java.lang.Double limit3)
    {
        this.limit3 = limit3;
    }

    /**
     * Return the value of the LIMIT4 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit4()
    {
        return this.limit4;
    }

    /**
     * Set the value of the LIMIT4 column.
     * @param limit4
     */
    public void setLimit4(java.lang.Double limit4)
    {
        this.limit4 = limit4;
    }

    /**
     * Return the value of the LIMIT5 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit5()
    {
        return this.limit5;
    }

    /**
     * Set the value of the LIMIT5 column.
     * @param limit5
     */
    public void setLimit5(java.lang.Double limit5)
    {
        this.limit5 = limit5;
    }

    /**
     * Return the value of the LIMIT6 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit6()
    {
        return this.limit6;
    }

    /**
     * Set the value of the LIMIT6 column.
     * @param limit6
     */
    public void setLimit6(java.lang.Double limit6)
    {
        this.limit6 = limit6;
    }

    /**
     * Return the value of the LIMIT7 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit7()
    {
        return this.limit7;
    }

    /**
     * Set the value of the LIMIT7 column.
     * @param limit7
     */
    public void setLimit7(java.lang.Double limit7)
    {
        this.limit7 = limit7;
    }

    /**
     * Return the value of the LIMIT8 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit8()
    {
        return this.limit8;
    }

    /**
     * Set the value of the LIMIT8 column.
     * @param limit8
     */
    public void setLimit8(java.lang.Double limit8)
    {
        this.limit8 = limit8;
    }

    /**
     * Return the value of the LIMIT9 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit9()
    {
        return this.limit9;
    }

    /**
     * Set the value of the LIMIT9 column.
     * @param limit9
     */
    public void setLimit9(java.lang.Double limit9)
    {
        this.limit9 = limit9;
    }

    /**
     * Return the value of the LIMIT10 column.
     * @return java.lang.Double
     */
    public java.lang.Double getLimit10()
    {
        return this.limit10;
    }

    /**
     * Set the value of the LIMIT10 column.
     * @param limit10
     */
    public void setLimit10(java.lang.Double limit10)
    {
        this.limit10 = limit10;
    }

    /**
     * Return the value of the LOGIN_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getLoginStatus()
    {
        return this.loginStatus;
    }

    /**
     * Set the value of the LOGIN_STATUS column.
     * @param loginStatus
     */
    public void setLoginStatus(java.lang.String loginStatus)
    {
        this.loginStatus = loginStatus;
    }

    /**
     * Return the value of the LOGIN_TIMES column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLoginTimes()
    {
        return this.loginTimes;
    }

    /**
     * Set the value of the LOGIN_TIMES column.
     * @param loginTimes
     */
    public void setLoginTimes(java.lang.Integer loginTimes)
    {
        this.loginTimes = loginTimes;
    }

    /**
     * Return the value of the LOGIN_FAIL_TIMES column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLoginFailTimes()
    {
        return this.loginFailTimes;
    }

    /**
     * Set the value of the LOGIN_FAIL_TIMES column.
     * @param loginFailTimes
     */
    public void setLoginFailTimes(java.lang.Integer loginFailTimes)
    {
        this.loginFailTimes = loginFailTimes;
    }

    /**
     * Return the value of the CURR_LOGIN_IP column.
     * @return java.lang.String
     */
    public java.lang.String getCurrLoginIp()
    {
        return this.currLoginIp;
    }

    /**
     * Set the value of the CURR_LOGIN_IP column.
     * @param currLoginIp
     */
    public void setCurrLoginIp(java.lang.String currLoginIp)
    {
        this.currLoginIp = currLoginIp;
    }

    /**
     * Return the value of the CURR_LOGIN_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getCurrLoginTime()
    {
        return this.currLoginTime;
    }

    /**
     * Set the value of the CURR_LOGIN_TIME column.
     * @param currLoginTime
     */
    public void setCurrLoginTime(java.util.Date currLoginTime)
    {
        this.currLoginTime = currLoginTime;
    }

    /**
     * Return the value of the PREV_LOGIN_IP column.
     * @return java.lang.String
     */
    public java.lang.String getPrevLoginIp()
    {
        return this.prevLoginIp;
    }

    /**
     * Set the value of the PREV_LOGIN_IP column.
     * @param prevLoginIp
     */
    public void setPrevLoginIp(java.lang.String prevLoginIp)
    {
        this.prevLoginIp = prevLoginIp;
    }

    /**
     * Return the value of the PREV_LOGIN_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getPrevLoginTime()
    {
        return this.prevLoginTime;
    }

    /**
     * Set the value of the PREV_LOGIN_TIME column.
     * @param prevLoginTime
     */
    public void setPrevLoginTime(java.util.Date prevLoginTime)
    {
        this.prevLoginTime = prevLoginTime;
    }

    /**
     * Return the value of the PERV_LOGIN_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getPervLoginStatus()
    {
        return this.pervLoginStatus;
    }

    /**
     * Set the value of the PERV_LOGIN_STATUS column.
     * @param pervLoginStatus
     */
    public void setPervLoginStatus(java.lang.String pervLoginStatus)
    {
        this.pervLoginStatus = pervLoginStatus;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the BLOCK_REASON column.
     * @return java.lang.String
     */
    public java.lang.String getBlockReason()
    {
        return this.blockReason;
    }

    /**
     * Set the value of the BLOCK_REASON column.
     * @param blockReason
     */
    public void setBlockReason(java.lang.String blockReason)
    {
        this.blockReason = blockReason;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the VERSION column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getVersion()
    {
        return this.version;
    }

    /**
     * Set the value of the VERSION column.
     * @param version
     */
    public void setVersion(java.lang.Integer version)
    {
        this.version = version;
    }

    /**
     * Return the value of the LAST_UPDATE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getLastUpdateTime()
    {
        return this.lastUpdateTime;
    }

    /**
     * Set the value of the LAST_UPDATE_TIME column.
     * @param lastUpdateTime
     */
    public void setLastUpdateTime(java.util.Date lastUpdateTime)
    {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * Return the value of the REQUESTER column.
     * @return java.lang.String
     */
    public java.lang.String getRequester()
    {
        return this.requester;
    }

    /**
     * Set the value of the REQUESTER column.
     * @param requester
     */
    public void setRequester(java.lang.String requester)
    {
        this.requester = requester;
    }

    /**
     * Return the value of the FULL_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getFullName()
    {
        return this.fullName;
    }

    /**
     * Set the value of the FULL_NAME column.
     * @param fullName
     */
    public void setFullName(java.lang.String fullName)
    {
        this.fullName = fullName;
    }

    /**
     * Return the value of the TITLE column.
     * @return java.lang.String
     */
    public java.lang.String getTitle()
    {
        return this.title;
    }

    /**
     * Set the value of the TITLE column.
     * @param title
     */
    public void setTitle(java.lang.String title)
    {
        this.title = title;
    }

    /**
     * Return the value of the GENDER column.
     * @return java.lang.String
     */
    public java.lang.String getGender()
    {
        return this.gender;
    }

    /**
     * Set the value of the GENDER column.
     * @param gender
     */
    public void setGender(java.lang.String gender)
    {
        this.gender = gender;
    }

    /**
     * Return the value of the ID_ISSUE_DATE column.
     * @return java.util.Date
     */
    public java.util.Date getIdIssueDate()
    {
        return this.idIssueDate;
    }

    /**
     * Set the value of the ID_ISSUE_DATE column.
     * @param idIssueDate
     */
    public void setIdIssueDate(java.util.Date idIssueDate)
    {
        this.idIssueDate = idIssueDate;
    }

    /**
     * Return the value of the ID_ISSUER column.
     * @return java.lang.String
     */
    public java.lang.String getIdIssuer()
    {
        return this.idIssuer;
    }

    /**
     * Set the value of the ID_ISSUER column.
     * @param idIssuer
     */
    public void setIdIssuer(java.lang.String idIssuer)
    {
        this.idIssuer = idIssuer;
    }

    /**
     * Return the value of the TELEPHONE column.
     * @return java.lang.String
     */
    public java.lang.String getTelephone()
    {
        return this.telephone;
    }

    /**
     * Set the value of the TELEPHONE column.
     * @param telephone
     */
    public void setTelephone(java.lang.String telephone)
    {
        this.telephone = telephone;
    }

    /**
     * Return the value of the MOBILE column.
     * @return java.lang.String
     */
    public java.lang.String getMobile()
    {
        return this.mobile;
    }

    /**
     * Set the value of the MOBILE column.
     * @param mobile
     */
    public void setMobile(java.lang.String mobile)
    {
        this.mobile = mobile;
    }

    /**
     * Return the value of the FAX_NO column.
     * @return java.lang.String
     */
    public java.lang.String getFaxNo()
    {
        return this.faxNo;
    }

    /**
     * Set the value of the FAX_NO column.
     * @param faxNo
     */
    public void setFaxNo(java.lang.String faxNo)
    {
        this.faxNo = faxNo;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
//    public boolean equals(Object rhs)
//    {
//        if (rhs == null)
//            return false;
//        if (! (rhs instanceof CorpUser))
//            return false;
//        CorpUser that = (CorpUser) rhs;
//        if (this.getUserId() == null || that.getUserId() == null)
//            return false;
//        return (this.getUserId().equals(that.getUserId()));
//    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
//    public int hashCode()
//    {
//        if (this.hashValue == 0)
//        {
//            int result = 17;
//            int userIdValue = this.getUserId() == null ? 0 : this.getUserId().hashCode();
//            result = result * 37 + userIdValue;
//            this.hashValue = result;
//        }
//        return this.hashValue;
//    }

	public java.lang.String getViewAllTransFlag() {
		return viewAllTransFlag;
	}

	public void setViewAllTransFlag(java.lang.String viewAllTransFlag) {
		this.viewAllTransFlag = viewAllTransFlag;
	}

	public java.lang.String getSecurityCode() {
		return securityCode;
	}

	public void setSecurityCode(java.lang.String securityCode) {
		this.securityCode = securityCode;
	}

	public java.lang.String getFinancialControllerFlag() {
		return financialControllerFlag;
	}

	public void setFinancialControllerFlag(java.lang.String financialControllerFlag) {
		this.financialControllerFlag = financialControllerFlag;
	}

	public java.lang.String getMerchantType() {
		return merchantType;
	}

	public void setMerchantType(java.lang.String merchantType) {
		this.merchantType = merchantType;
	}

	public java.lang.String getCertCardType() {
		return certCardType;
	}

	public void setCertCardType(java.lang.String certCardType) {
		this.certCardType = certCardType;
	}

	public java.lang.String getMobileCountryCode() {
		return mobileCountryCode;
	}

	public void setMobileCountryCode(java.lang.String mobileCountryCode) {
		this.mobileCountryCode = mobileCountryCode;
	}

	public java.lang.String getMobileAreaCode() {
		return mobileAreaCode;
	}

	public void setMobileAreaCode(java.lang.String mobileAreaCode) {
		this.mobileAreaCode = mobileAreaCode;
	}

	public CorpUserId getId() {
		return id;
	}

	public void setId(CorpUserId id) {
		this.id = id;
	}

}
