/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Dec 29 23:21:58 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.bat;

import java.io.Serializable;

/**
 * A class that represents a row in the PAYROLL table. 
 * You can customize the behavior of this class by editing the class, {@link Payroll()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractPayroll 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String payrollId;

    /** The value of the simple originatorAcNo property. */
    private java.lang.String originatorAcNo;

    /** The value of the simple groupId property. */
    private java.lang.String groupId;

    /** The value of the simple startValueDate property. */
    private java.lang.String startValueDate;

    /** The value of the simple endValueDate property. */
    private java.lang.String endValueDate;

    /** The value of the simple volumeNo property. */
    private java.lang.String volumeNo;

    /** The value of the simple filler1 property. */
    private java.lang.String filler1;

    /** The value of the simple batchNo property. */
    private java.lang.String batchNo;

    /** The value of the simple batchDate property. */
    private java.lang.String batchDate;

    /** The value of the simple totalNumber property. */
    private java.lang.Integer totalNumber;

    /** The value of the simple totalAmount property. */
    private java.lang.Double totalAmount;

    /** The value of the simple filler2 property. */
    private java.lang.String filler2;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple fileName property. */
    private java.lang.String fileName;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple requestTime property. */
    private java.util.Date requestTime;

    /** The value of the simple executeTime property. */
    private java.util.Date executeTime;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple batchResult property. */
    private java.lang.String batchResult;
    
    //add by linrui 20180307 for cbd check payroll result /detail
    private java.lang.String acDate;
    private java.lang.String jrnNo;
    private java.lang.String haddownHis;
    public java.lang.String getAcDate() {
		return acDate;
	}

	public void setAcDate(java.lang.String acDate) {
		this.acDate = acDate;
	}

	public java.lang.String getJrnNo() {
		return jrnNo;
	}

	public void setJrnNo(java.lang.String jrnNo) {
		this.jrnNo = jrnNo;
	}

	public java.lang.String getHaddownHis() {
		return haddownHis;
	}

	public void setHaddownHis(java.lang.String haddownHis) {
		this.haddownHis = haddownHis;
	}
	//end
    /**
     * Simple constructor of AbstractPayroll instances.
     */
    public AbstractPayroll()
    {
    }

    /**
     * Constructor of AbstractPayroll instances given a simple primary key.
     * @param payrollId
     */
    public AbstractPayroll(java.lang.String payrollId)
    {
        this.setPayrollId(payrollId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getPayrollId()
    {
        return payrollId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param payrollId
     */
    public void setPayrollId(java.lang.String payrollId)
    {
        this.hashValue = 0;
        this.payrollId = payrollId;
    }

    /**
     * Return the value of the ORIGINATOR_AC_NO column.
     * @return java.lang.String
     */
    public java.lang.String getOriginatorAcNo()
    {
        return this.originatorAcNo;
    }

    /**
     * Set the value of the ORIGINATOR_AC_NO column.
     * @param originatorAcNo
     */
    public void setOriginatorAcNo(java.lang.String originatorAcNo)
    {
        this.originatorAcNo = originatorAcNo;
    }

    /**
     * Return the value of the GROUP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getGroupId()
    {
        return this.groupId;
    }

    /**
     * Set the value of the GROUP_ID column.
     * @param groupId
     */
    public void setGroupId(java.lang.String groupId)
    {
        this.groupId = groupId;
    }

    /**
     * Return the value of the START_VALUE_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getStartValueDate()
    {
        return this.startValueDate;
    }

    /**
     * Set the value of the START_VALUE_DATE column.
     * @param startValueDate
     */
    public void setStartValueDate(java.lang.String startValueDate)
    {
        this.startValueDate = startValueDate;
    }

    /**
     * Return the value of the END_VALUE_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getEndValueDate()
    {
        return this.endValueDate;
    }

    /**
     * Set the value of the END_VALUE_DATE column.
     * @param endValueDate
     */
    public void setEndValueDate(java.lang.String endValueDate)
    {
        this.endValueDate = endValueDate;
    }

    /**
     * Return the value of the VOLUME_NO column.
     * @return java.lang.String
     */
    public java.lang.String getVolumeNo()
    {
        return this.volumeNo;
    }

    /**
     * Set the value of the VOLUME_NO column.
     * @param volumeNo
     */
    public void setVolumeNo(java.lang.String volumeNo)
    {
        this.volumeNo = volumeNo;
    }

    /**
     * Return the value of the FILLER_1 column.
     * @return java.lang.String
     */
    public java.lang.String getFiller1()
    {
        return this.filler1;
    }

    /**
     * Set the value of the FILLER_1 column.
     * @param filler1
     */
    public void setFiller1(java.lang.String filler1)
    {
        this.filler1 = filler1;
    }

    /**
     * Return the value of the BATCH_NO column.
     * @return java.lang.String
     */
    public java.lang.String getBatchNo()
    {
        return this.batchNo;
    }

    /**
     * Set the value of the BATCH_NO column.
     * @param batchNo
     */
    public void setBatchNo(java.lang.String batchNo)
    {
        this.batchNo = batchNo;
    }

    /**
     * Return the value of the BATCH_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getBatchDate()
    {
        return this.batchDate;
    }

    /**
     * Set the value of the BATCH_DATE column.
     * @param batchDate
     */
    public void setBatchDate(java.lang.String batchDate)
    {
        this.batchDate = batchDate;
    }

    /**
     * Return the value of the TOTAL_NUMBER column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getTotalNumber()
    {
        return this.totalNumber;
    }

    /**
     * Set the value of the TOTAL_NUMBER column.
     * @param totalNumber
     */
    public void setTotalNumber(java.lang.Integer totalNumber)
    {
        this.totalNumber = totalNumber;
    }

    /**
     * Return the value of the TOTAL_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getTotalAmount()
    {
        return this.totalAmount;
    }

    /**
     * Set the value of the TOTAL_AMOUNT column.
     * @param totalAmount
     */
    public void setTotalAmount(java.lang.Double totalAmount)
    {
        this.totalAmount = totalAmount;
    }

    /**
     * Return the value of the FILLER_2 column.
     * @return java.lang.String
     */
    public java.lang.String getFiller2()
    {
        return this.filler2;
    }

    /**
     * Set the value of the FILLER_2 column.
     * @param filler2
     */
    public void setFiller2(java.lang.String filler2)
    {
        this.filler2 = filler2;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the FILE_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getFileName()
    {
        return this.fileName;
    }

    /**
     * Set the value of the FILE_NAME column.
     * @param fileName
     */
    public void setFileName(java.lang.String fileName)
    {
        this.fileName = fileName;
    }

    /**
     * Return the value of the REMARK column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the REQUEST_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getRequestTime()
    {
        return this.requestTime;
    }

    /**
     * Set the value of the REQUEST_TIME column.
     * @param requestTime
     */
    public void setRequestTime(java.util.Date requestTime)
    {
        this.requestTime = requestTime;
    }

    /**
     * Return the value of the EXECUTE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getExecuteTime()
    {
        return this.executeTime;
    }

    /**
     * Set the value of the EXECUTE_TIME column.
     * @param executeTime
     */
    public void setExecuteTime(java.util.Date executeTime)
    {
        this.executeTime = executeTime;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the BATCH_RESULT column.
     * @return java.lang.String
     */
    public java.lang.String getBatchResult()
    {
        return this.batchResult;
    }

    /**
     * Set the value of the BATCH_RESULT column.
     * @param batchResult
     */
    public void setBatchResult(java.lang.String batchResult)
    {
        this.batchResult = batchResult;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Payroll))
            return false;
        Payroll that = (Payroll) rhs;
        if (this.getPayrollId() == null || that.getPayrollId() == null)
            return false;
        return (this.getPayrollId().equals(that.getPayrollId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int payrollIdValue = this.getPayrollId() == null ? 0 : this.getPayrollId().hashCode();
            result = result * 37 + payrollIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
