/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Dec 29 23:23:31 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.bat;

import java.io.Serializable;

/**
 * A class that represents a row in the TRANSFER_MACAU_STM table. 
 * You can customize the behavior of this class by editing the class, {@link TransferMacauStm()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTransferMacauStm 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String transId;

    /** The value of the simple recordType property. */
    private java.lang.String recordType;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple networkType property. */
    private java.lang.String networkType;

    /** The value of the simple benbankSwiab property. */
    private java.lang.String benbankSwiab;

    /** The value of the simple beneficiaryCountry property. */
    private java.lang.String beneficiaryCountry;

    /** The value of the simple fromAccount property. */
    private java.lang.String fromAccount;

    /** The value of the simple toAccount property. */
    private java.lang.String toAccount;

    /** The value of the simple beneficiaryName property. */
    private java.lang.String beneficiaryName;

    /** The value of the simple beneficiaryBank property. */
    private java.lang.String beneficiaryBank;

    /** The value of the simple beneficiaryBankAdd1 property. */
    private java.lang.String beneficiaryBankAdd1;

    /** The value of the simple beneficiaryBankAdd2 property. */
    private java.lang.String beneficiaryBankAdd2;

    /** The value of the simple beneficiaryBankAdd3 property. */
    private java.lang.String beneficiaryBankAdd3;

    /** The value of the simple senderReference property. */
    private java.lang.String senderReference;

    /** The value of the simple bankCode property. */
    private java.lang.String bankCode;

    /** The value of the simple chipsVid property. */
    private java.lang.String chipsVid;

    /** The value of the simple intermediaryBank property. */
    private java.lang.String intermediaryBank;

    /** The value of the simple inteBankAccount property. */
    private java.lang.String inteBankAccount;

    /** The value of the simple inteBankSwift property. */
    private java.lang.String inteBankSwift;

    /** The value of the simple inteBankAdd1 property. */
    private java.lang.String inteBankAdd1;

    /** The value of the simple inteBankAdd2 property. */
    private java.lang.String inteBankAdd2;

    /** The value of the simple inteBankAdd3 property. */
    private java.lang.String inteBankAdd3;

    /** The value of the simple message property. */
    private java.lang.String message;

    /** The value of the simple transferAmount property. */
    private java.lang.Double transferAmount;

    /** The value of the simple debitAmount property. */
    private java.lang.Double debitAmount;

    /** The value of the simple inputAmountFlag property. */
    private java.lang.String inputAmountFlag;

    /** The value of the simple requestType property. */
    private java.lang.String requestType;

    /** The value of the simple transferDate property. */
    private java.util.Date transferDate;

    /** The value of the simple chargeBy property. */
    private java.lang.String chargeBy;

    /** The value of the simple chargeAccount property. */
    private java.lang.String chargeAccount;

    /** The value of the simple messsage property. */
    private java.lang.String messsage;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple requestTime property. */
    private java.util.Date requestTime;

    /** The value of the simple executeTime property. */
    private java.util.Date executeTime;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple toCurrency property. */
    private java.lang.String toCurrency;

    /** The value of the simple fromCurrency property. */
    private java.lang.String fromCurrency;

    /** The value of the simple chargeAmount property. */
    private java.lang.Double chargeAmount;

    /** The value of the simple exchangeRate property. */
    private java.lang.Double exchangeRate;

    /** The value of the simple chargeCurrency property. */
    private java.lang.String chargeCurrency;

    /** The value of the simple problemType property. */
    private java.lang.String problemType;

    /** The value of the simple batchId property. */
    private java.lang.String batchId;

    /** The value of the simple filler property. */
    private java.lang.String filler;

    /** The value of the simple lineNo property. */
    private java.lang.Integer lineNo;

    /** The value of the simple bankReferenceNumber property. */
    private java.lang.String bankReferenceNumber;

    /** The value of the simple detailResult property. */
    private java.lang.String detailResult;

    /** The value of the simple rejectReason property. */
    private java.lang.String rejectReason;

    //------------added by xyf 20090804 begin---------------
    /** The value of the simple beneficiaryName property. */
    private java.lang.String beneficiaryName2;
    //------------added by xyf 20090804 begin---------------
    
    
    public java.lang.String getBeneficiaryName2() {
		return beneficiaryName2;
	}

	public void setBeneficiaryName2(java.lang.String beneficiaryName2) {
		this.beneficiaryName2 = beneficiaryName2;
	}

	/**
     * Simple constructor of AbstractTransferMacauStm instances.
     */
    public AbstractTransferMacauStm()
    {
    }

    /**
     * Constructor of AbstractTransferMacauStm instances given a simple primary key.
     * @param transId
     */
    public AbstractTransferMacauStm(java.lang.String transId)
    {
        this.setTransId(transId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getTransId()
    {
        return transId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param transId
     */
    public void setTransId(java.lang.String transId)
    {
        this.hashValue = 0;
        this.transId = transId;
    }

    /**
     * Return the value of the RECORD_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getRecordType()
    {
        return this.recordType;
    }

    /**
     * Set the value of the RECORD_TYPE column.
     * @param recordType
     */
    public void setRecordType(java.lang.String recordType)
    {
        this.recordType = recordType;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the NETWORK_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getNetworkType()
    {
        return this.networkType;
    }

    /**
     * Set the value of the NETWORK_TYPE column.
     * @param networkType
     */
    public void setNetworkType(java.lang.String networkType)
    {
        this.networkType = networkType;
    }

    /**
     * Return the value of the BENBANK_SWIAB column.
     * @return java.lang.String
     */
    public java.lang.String getBenbankSwiab()
    {
        return this.benbankSwiab;
    }

    /**
     * Set the value of the BENBANK_SWIAB column.
     * @param benbankSwiab
     */
    public void setBenbankSwiab(java.lang.String benbankSwiab)
    {
        this.benbankSwiab = benbankSwiab;
    }

    /**
     * Return the value of the BENEFICIARY_COUNTRY column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryCountry()
    {
        return this.beneficiaryCountry;
    }

    /**
     * Set the value of the BENEFICIARY_COUNTRY column.
     * @param beneficiaryCountry
     */
    public void setBeneficiaryCountry(java.lang.String beneficiaryCountry)
    {
        this.beneficiaryCountry = beneficiaryCountry;
    }

    /**
     * Return the value of the FROM_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getFromAccount()
    {
        return this.fromAccount;
    }

    /**
     * Set the value of the FROM_ACCOUNT column.
     * @param fromAccount
     */
    public void setFromAccount(java.lang.String fromAccount)
    {
        this.fromAccount = fromAccount;
    }

    /**
     * Return the value of the TO_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getToAccount()
    {
        return this.toAccount;
    }

    /**
     * Set the value of the TO_ACCOUNT column.
     * @param toAccount
     */
    public void setToAccount(java.lang.String toAccount)
    {
        this.toAccount = toAccount;
    }

    /**
     * Return the value of the BENEFICIARY_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryName()
    {
        return this.beneficiaryName;
    }

    /**
     * Set the value of the BENEFICIARY_NAME column.
     * @param beneficiaryName
     */
    public void setBeneficiaryName(java.lang.String beneficiaryName)
    {
        this.beneficiaryName = beneficiaryName;
    }

    /**
     * Return the value of the BENEFICIARY_BANK column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryBank()
    {
        return this.beneficiaryBank;
    }

    /**
     * Set the value of the BENEFICIARY_BANK column.
     * @param beneficiaryBank
     */
    public void setBeneficiaryBank(java.lang.String beneficiaryBank)
    {
        this.beneficiaryBank = beneficiaryBank;
    }

    /**
     * Return the value of the BENEFICIARY_BANK_ADD1 column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryBankAdd1()
    {
        return this.beneficiaryBankAdd1;
    }

    /**
     * Set the value of the BENEFICIARY_BANK_ADD1 column.
     * @param beneficiaryBankAdd1
     */
    public void setBeneficiaryBankAdd1(java.lang.String beneficiaryBankAdd1)
    {
        this.beneficiaryBankAdd1 = beneficiaryBankAdd1;
    }

    /**
     * Return the value of the BENEFICIARY_BANK_ADD2 column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryBankAdd2()
    {
        return this.beneficiaryBankAdd2;
    }

    /**
     * Set the value of the BENEFICIARY_BANK_ADD2 column.
     * @param beneficiaryBankAdd2
     */
    public void setBeneficiaryBankAdd2(java.lang.String beneficiaryBankAdd2)
    {
        this.beneficiaryBankAdd2 = beneficiaryBankAdd2;
    }

    /**
     * Return the value of the BENEFICIARY_BANK_ADD3 column.
     * @return java.lang.String
     */
    public java.lang.String getBeneficiaryBankAdd3()
    {
        return this.beneficiaryBankAdd3;
    }

    /**
     * Set the value of the BENEFICIARY_BANK_ADD3 column.
     * @param beneficiaryBankAdd3
     */
    public void setBeneficiaryBankAdd3(java.lang.String beneficiaryBankAdd3)
    {
        this.beneficiaryBankAdd3 = beneficiaryBankAdd3;
    }

    /**
     * Return the value of the SENDER_REFERENCE column.
     * @return java.lang.String
     */
    public java.lang.String getSenderReference()
    {
        return this.senderReference;
    }

    /**
     * Set the value of the SENDER_REFERENCE column.
     * @param senderReference
     */
    public void setSenderReference(java.lang.String senderReference)
    {
        this.senderReference = senderReference;
    }

    /**
     * Return the value of the BANK_CODE column.
     * @return java.lang.String
     */
    public java.lang.String getBankCode()
    {
        return this.bankCode;
    }

    /**
     * Set the value of the BANK_CODE column.
     * @param bankCode
     */
    public void setBankCode(java.lang.String bankCode)
    {
        this.bankCode = bankCode;
    }

    /**
     * Return the value of the CHIPS_VID column.
     * @return java.lang.String
     */
    public java.lang.String getChipsVid()
    {
        return this.chipsVid;
    }

    /**
     * Set the value of the CHIPS_VID column.
     * @param chipsVid
     */
    public void setChipsVid(java.lang.String chipsVid)
    {
        this.chipsVid = chipsVid;
    }

    /**
     * Return the value of the INTERMEDIARY_BANK column.
     * @return java.lang.String
     */
    public java.lang.String getIntermediaryBank()
    {
        return this.intermediaryBank;
    }

    /**
     * Set the value of the INTERMEDIARY_BANK column.
     * @param intermediaryBank
     */
    public void setIntermediaryBank(java.lang.String intermediaryBank)
    {
        this.intermediaryBank = intermediaryBank;
    }

    /**
     * Return the value of the INTE_BANK_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getInteBankAccount()
    {
        return this.inteBankAccount;
    }

    /**
     * Set the value of the INTE_BANK_ACCOUNT column.
     * @param inteBankAccount
     */
    public void setInteBankAccount(java.lang.String inteBankAccount)
    {
        this.inteBankAccount = inteBankAccount;
    }

    /**
     * Return the value of the INTE_BANK_SWIFT column.
     * @return java.lang.String
     */
    public java.lang.String getInteBankSwift()
    {
        return this.inteBankSwift;
    }

    /**
     * Set the value of the INTE_BANK_SWIFT column.
     * @param inteBankSwift
     */
    public void setInteBankSwift(java.lang.String inteBankSwift)
    {
        this.inteBankSwift = inteBankSwift;
    }

    /**
     * Return the value of the INTE_BANK_ADD1 column.
     * @return java.lang.String
     */
    public java.lang.String getInteBankAdd1()
    {
        return this.inteBankAdd1;
    }

    /**
     * Set the value of the INTE_BANK_ADD1 column.
     * @param inteBankAdd1
     */
    public void setInteBankAdd1(java.lang.String inteBankAdd1)
    {
        this.inteBankAdd1 = inteBankAdd1;
    }

    /**
     * Return the value of the INTE_BANK_ADD2 column.
     * @return java.lang.String
     */
    public java.lang.String getInteBankAdd2()
    {
        return this.inteBankAdd2;
    }

    /**
     * Set the value of the INTE_BANK_ADD2 column.
     * @param inteBankAdd2
     */
    public void setInteBankAdd2(java.lang.String inteBankAdd2)
    {
        this.inteBankAdd2 = inteBankAdd2;
    }

    /**
     * Return the value of the INTE_BANK_ADD3 column.
     * @return java.lang.String
     */
    public java.lang.String getInteBankAdd3()
    {
        return this.inteBankAdd3;
    }

    /**
     * Set the value of the INTE_BANK_ADD3 column.
     * @param inteBankAdd3
     */
    public void setInteBankAdd3(java.lang.String inteBankAdd3)
    {
        this.inteBankAdd3 = inteBankAdd3;
    }

    /**
     * Return the value of the MESSAGE column.
     * @return java.lang.String
     */
    public java.lang.String getMessage()
    {
        return this.message;
    }

    /**
     * Set the value of the MESSAGE column.
     * @param message
     */
    public void setMessage(java.lang.String message)
    {
        this.message = message;
    }

    /**
     * Return the value of the TRANSFER_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getTransferAmount()
    {
        return this.transferAmount;
    }

    /**
     * Set the value of the TRANSFER_AMOUNT column.
     * @param transferAmount
     */
    public void setTransferAmount(java.lang.Double transferAmount)
    {
        this.transferAmount = transferAmount;
    }

    /**
     * Return the value of the DEBIT_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getDebitAmount()
    {
        return this.debitAmount;
    }

    /**
     * Set the value of the DEBIT_AMOUNT column.
     * @param debitAmount
     */
    public void setDebitAmount(java.lang.Double debitAmount)
    {
        this.debitAmount = debitAmount;
    }

    /**
     * Return the value of the INPUT_AMOUNT_FLAG column.
     * @return java.lang.String
     */
    public java.lang.String getInputAmountFlag()
    {
        return this.inputAmountFlag;
    }

    /**
     * Set the value of the INPUT_AMOUNT_FLAG column.
     * @param inputAmountFlag
     */
    public void setInputAmountFlag(java.lang.String inputAmountFlag)
    {
        this.inputAmountFlag = inputAmountFlag;
    }

    /**
     * Return the value of the REQUEST_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getRequestType()
    {
        return this.requestType;
    }

    /**
     * Set the value of the REQUEST_TYPE column.
     * @param requestType
     */
    public void setRequestType(java.lang.String requestType)
    {
        this.requestType = requestType;
    }

    /**
     * Return the value of the TRANSFER_DATE column.
     * @return java.util.Date
     */
    public java.util.Date getTransferDate()
    {
        return this.transferDate;
    }

    /**
     * Set the value of the TRANSFER_DATE column.
     * @param transferDate
     */
    public void setTransferDate(java.util.Date transferDate)
    {
        this.transferDate = transferDate;
    }

    /**
     * Return the value of the CHARGE_BY column.
     * @return java.lang.String
     */
    public java.lang.String getChargeBy()
    {
        return this.chargeBy;
    }

    /**
     * Set the value of the CHARGE_BY column.
     * @param chargeBy
     */
    public void setChargeBy(java.lang.String chargeBy)
    {
        this.chargeBy = chargeBy;
    }

    /**
     * Return the value of the CHARGE_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getChargeAccount()
    {
        return this.chargeAccount;
    }

    /**
     * Set the value of the CHARGE_ACCOUNT column.
     * @param chargeAccount
     */
    public void setChargeAccount(java.lang.String chargeAccount)
    {
        this.chargeAccount = chargeAccount;
    }

    /**
     * Return the value of the MESSSAGE column.
     * @return java.lang.String
     */
    public java.lang.String getMesssage()
    {
        return this.messsage;
    }

    /**
     * Set the value of the MESSSAGE column.
     * @param messsage
     */
    public void setMesssage(java.lang.String messsage)
    {
        this.messsage = messsage;
    }

    /**
     * Return the value of the REMARK column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the REQUEST_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getRequestTime()
    {
        return this.requestTime;
    }

    /**
     * Set the value of the REQUEST_TIME column.
     * @param requestTime
     */
    public void setRequestTime(java.util.Date requestTime)
    {
        this.requestTime = requestTime;
    }

    /**
     * Return the value of the EXECUTE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getExecuteTime()
    {
        return this.executeTime;
    }

    /**
     * Set the value of the EXECUTE_TIME column.
     * @param executeTime
     */
    public void setExecuteTime(java.util.Date executeTime)
    {
        this.executeTime = executeTime;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the TO_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getToCurrency()
    {
        return this.toCurrency;
    }

    /**
     * Set the value of the TO_CURRENCY column.
     * @param toCurrency
     */
    public void setToCurrency(java.lang.String toCurrency)
    {
        this.toCurrency = toCurrency;
    }

    /**
     * Return the value of the FROM_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getFromCurrency()
    {
        return this.fromCurrency;
    }

    /**
     * Set the value of the FROM_CURRENCY column.
     * @param fromCurrency
     */
    public void setFromCurrency(java.lang.String fromCurrency)
    {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Return the value of the CHARGE_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getChargeAmount()
    {
        return this.chargeAmount;
    }

    /**
     * Set the value of the CHARGE_AMOUNT column.
     * @param chargeAmount
     */
    public void setChargeAmount(java.lang.Double chargeAmount)
    {
        this.chargeAmount = chargeAmount;
    }

    /**
     * Return the value of the EXCHANGE_RATE column.
     * @return java.lang.Double
     */
    public java.lang.Double getExchangeRate()
    {
        return this.exchangeRate;
    }

    /**
     * Set the value of the EXCHANGE_RATE column.
     * @param exchangeRate
     */
    public void setExchangeRate(java.lang.Double exchangeRate)
    {
        this.exchangeRate = exchangeRate;
    }

    /**
     * Return the value of the CHARGE_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getChargeCurrency()
    {
        return this.chargeCurrency;
    }

    /**
     * Set the value of the CHARGE_CURRENCY column.
     * @param chargeCurrency
     */
    public void setChargeCurrency(java.lang.String chargeCurrency)
    {
        this.chargeCurrency = chargeCurrency;
    }

    /**
     * Return the value of the PROBLEM_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getProblemType()
    {
        return this.problemType;
    }

    /**
     * Set the value of the PROBLEM_TYPE column.
     * @param problemType
     */
    public void setProblemType(java.lang.String problemType)
    {
        this.problemType = problemType;
    }

    /**
     * Return the value of the BATCH_ID column.
     * @return java.lang.String
     */
    public java.lang.String getBatchId()
    {
        return this.batchId;
    }

    /**
     * Set the value of the BATCH_ID column.
     * @param batchId
     */
    public void setBatchId(java.lang.String batchId)
    {
        this.batchId = batchId;
    }

    /**
     * Return the value of the FILLER column.
     * @return java.lang.String
     */
    public java.lang.String getFiller()
    {
        return this.filler;
    }

    /**
     * Set the value of the FILLER column.
     * @param filler
     */
    public void setFiller(java.lang.String filler)
    {
        this.filler = filler;
    }

    /**
     * Return the value of the LINE_NO column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLineNo()
    {
        return this.lineNo;
    }

    /**
     * Set the value of the LINE_NO column.
     * @param lineNo
     */
    public void setLineNo(java.lang.Integer lineNo)
    {
        this.lineNo = lineNo;
    }

    /**
     * Return the value of the BANK_REFERENCE_NUMBER column.
     * @return java.lang.String
     */
    public java.lang.String getBankReferenceNumber()
    {
        return this.bankReferenceNumber;
    }

    /**
     * Set the value of the BANK_REFERENCE_NUMBER column.
     * @param bankReferenceNumber
     */
    public void setBankReferenceNumber(java.lang.String bankReferenceNumber)
    {
        this.bankReferenceNumber = bankReferenceNumber;
    }

    /**
     * Return the value of the DETAIL_RESULT column.
     * @return java.lang.String
     */
    public java.lang.String getDetailResult()
    {
        return this.detailResult;
    }

    /**
     * Set the value of the DETAIL_RESULT column.
     * @param detailResult
     */
    public void setDetailResult(java.lang.String detailResult)
    {
        this.detailResult = detailResult;
    }

    /**
     * Return the value of the REJECT_REASON column.
     * @return java.lang.String
     */
    public java.lang.String getRejectReason()
    {
        return this.rejectReason;
    }

    /**
     * Set the value of the REJECT_REASON column.
     * @param rejectReason
     */
    public void setRejectReason(java.lang.String rejectReason)
    {
        this.rejectReason = rejectReason;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof TransferMacauStm))
            return false;
        TransferMacauStm that = (TransferMacauStm) rhs;
        if (this.getTransId() == null || that.getTransId() == null)
            return false;
        return (this.getTransId().equals(that.getTransId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int transIdValue = this.getTransId() == null ? 0 : this.getTransId().hashCode();
            result = result * 37 + transIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
