/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Dec 29 23:21:28 CST 2006 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.bat;

import java.io.Serializable;

/**
 * A class that represents a row in the FILE_REQUEST table. 
 * You can customize the behavior of this class by editing the class, {@link FileRequest()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractFileRequest 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String batchId;

    /** The value of the simple batchType property. */
    private java.lang.String batchType;

    /** The value of the simple orderDate property. */
    private java.lang.String orderDate;

    /** The value of the simple fromAccount property. */
    private java.lang.String fromAccount;

    /** The value of the simple currency property. */
    private java.lang.String currency;

    /** The value of the simple fromAmount property. */
    private java.lang.Double fromAmount;

    /** The value of the simple totalNumber property. */
    private java.lang.Integer totalNumber;

    /** The value of the simple batchReference property. */
    private java.lang.String batchReference;

    /** The value of the simple fileName property. */
    private java.lang.String fileName;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple corpId property. */
    private java.lang.String corpId;

    /** The value of the simple userId property. */
    private java.lang.String userId;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple requestTime property. */
    private java.util.Date requestTime;

    /** The value of the simple executeTime property. */
    private java.util.Date executeTime;

    /** The value of the simple chargeAccount property. */
    private java.lang.String chargeAccount;

    /** The value of the simple chargeFlag property. */
    private java.lang.String chargeFlag;

    /** The value of the simple authStatus property. */
    private java.lang.String authStatus;

    /** The value of the simple operation property. */
    private java.lang.String operation;

    /** The value of the simple toAccount property. */
    private java.lang.String toAccount;

    /** The value of the simple toAmount property. */
    private java.lang.Double toAmount;

    /** The value of the simple batchStatus property. */
    private java.lang.String batchStatus;

    /** The value of the simple fromCurrency property. */
    private java.lang.String fromCurrency;

    /** The value of the simple toCurrency property. */
    private java.lang.String toCurrency;

    /** The value of the simple chargeCurrency property. */
    private java.lang.String chargeCurrency;

    /** The value of the simple totalChargesamount property. */
    private java.lang.Double totalChargesamount;

    /** The value of the simple companyName property. */
    private java.lang.String companyName;

    /** The value of the simple filler property. */
    private java.lang.String filler;

    /** The value of the simple batchResult property. */
    private java.lang.String batchResult;
       
    //Add by heyongjiang 2010-04-22
    private java.lang.String toAccountName;    
    private java.lang.String toAccountName2;
    
    /**
     * Get toAccountName
     * @return toAccountName
     */
    public java.lang.String getToAccountName()
    {
        return toAccountName;
    }
    
    /**
     * Get toAccountName2
     * @return toAccountName2
     */
    public java.lang.String getToAccountName2()
    {
        return toAccountName2;
    }
    
    /**
     * Set toAccountName
     * @param toAccountName
     */
    public void setToAccountName(java.lang.String toAccountName)
    {
        this.toAccountName = toAccountName;
    }
    
    /**
     * Set toAccountName2
     * @param toAccountName2
     */
    public void setToAccountName2(java.lang.String toAccountName2)
    {
        this.toAccountName2 = toAccountName2;
    }//Add by heyongjiang end

    /**
     * Simple constructor of AbstractFileRequest instances.
     */
    public AbstractFileRequest()
    {
    }

    /**
     * Constructor of AbstractFileRequest instances given a simple primary key.
     * @param batchId
     */
    public AbstractFileRequest(java.lang.String batchId)
    {
        this.setBatchId(batchId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getBatchId()
    {
        return batchId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param batchId
     */
    public void setBatchId(java.lang.String batchId)
    {
        this.hashValue = 0;
        this.batchId = batchId;
    }

    /**
     * Return the value of the BATCH_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getBatchType()
    {
        return this.batchType;
    }

    /**
     * Set the value of the BATCH_TYPE column.
     * @param batchType
     */
    public void setBatchType(java.lang.String batchType)
    {
        this.batchType = batchType;
    }

    /**
     * Return the value of the ORDER_DATE column.
     * @return java.lang.String
     */
    public java.lang.String getOrderDate()
    {
        return this.orderDate;
    }

    /**
     * Set the value of the ORDER_DATE column.
     * @param orderDate
     */
    public void setOrderDate(java.lang.String orderDate)
    {
        this.orderDate = orderDate;
    }

    /**
     * Return the value of the FROM_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getFromAccount()
    {
        return this.fromAccount;
    }

    /**
     * Set the value of the FROM_ACCOUNT column.
     * @param fromAccount
     */
    public void setFromAccount(java.lang.String fromAccount)
    {
        this.fromAccount = fromAccount;
    }

    /**
     * Return the value of the CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getCurrency()
    {
        return this.currency;
    }

    /**
     * Set the value of the CURRENCY column.
     * @param currency
     */
    public void setCurrency(java.lang.String currency)
    {
        this.currency = currency;
    }

    /**
     * Return the value of the FROM_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getFromAmount()
    {
        return this.fromAmount;
    }

    /**
     * Set the value of the FROM_AMOUNT column.
     * @param fromAmount
     */
    public void setFromAmount(java.lang.Double fromAmount)
    {
        this.fromAmount = fromAmount;
    }

    /**
     * Return the value of the TOTAL_NUMBER column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getTotalNumber()
    {
        return this.totalNumber;
    }

    /**
     * Set the value of the TOTAL_NUMBER column.
     * @param totalNumber
     */
    public void setTotalNumber(java.lang.Integer totalNumber)
    {
        this.totalNumber = totalNumber;
    }

    /**
     * Return the value of the BATCH_REFERENCE column.
     * @return java.lang.String
     */
    public java.lang.String getBatchReference()
    {
        return this.batchReference;
    }

    /**
     * Set the value of the BATCH_REFERENCE column.
     * @param batchReference
     */
    public void setBatchReference(java.lang.String batchReference)
    {
        this.batchReference = batchReference;
    }

    /**
     * Return the value of the FILE_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getFileName()
    {
        return this.fileName;
    }

    /**
     * Set the value of the FILE_NAME column.
     * @param fileName
     */
    public void setFileName(java.lang.String fileName)
    {
        this.fileName = fileName;
    }

    /**
     * Return the value of the REMARK column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the REMARK column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the CORP_ID column.
     * @return java.lang.String
     */
    public java.lang.String getCorpId()
    {
        return this.corpId;
    }

    /**
     * Set the value of the CORP_ID column.
     * @param corpId
     */
    public void setCorpId(java.lang.String corpId)
    {
        this.corpId = corpId;
    }

    /**
     * Return the value of the USER_ID column.
     * @return java.lang.String
     */
    public java.lang.String getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the USER_ID column.
     * @param userId
     */
    public void setUserId(java.lang.String userId)
    {
        this.userId = userId;
    }

    /**
     * Return the value of the STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the STATUS column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the REQUEST_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getRequestTime()
    {
        return this.requestTime;
    }

    /**
     * Set the value of the REQUEST_TIME column.
     * @param requestTime
     */
    public void setRequestTime(java.util.Date requestTime)
    {
        this.requestTime = requestTime;
    }

    /**
     * Return the value of the EXECUTE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getExecuteTime()
    {
        return this.executeTime;
    }

    /**
     * Set the value of the EXECUTE_TIME column.
     * @param executeTime
     */
    public void setExecuteTime(java.util.Date executeTime)
    {
        this.executeTime = executeTime;
    }

    /**
     * Return the value of the CHARGE_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getChargeAccount()
    {
        return this.chargeAccount;
    }

    /**
     * Set the value of the CHARGE_ACCOUNT column.
     * @param chargeAccount
     */
    public void setChargeAccount(java.lang.String chargeAccount)
    {
        this.chargeAccount = chargeAccount;
    }

    /**
     * Return the value of the CHARGE_FLAG column.
     * @return java.lang.String
     */
    public java.lang.String getChargeFlag()
    {
        return this.chargeFlag;
    }

    /**
     * Set the value of the CHARGE_FLAG column.
     * @param chargeFlag
     */
    public void setChargeFlag(java.lang.String chargeFlag)
    {
        this.chargeFlag = chargeFlag;
    }

    /**
     * Return the value of the AUTH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getAuthStatus()
    {
        return this.authStatus;
    }

    /**
     * Set the value of the AUTH_STATUS column.
     * @param authStatus
     */
    public void setAuthStatus(java.lang.String authStatus)
    {
        this.authStatus = authStatus;
    }

    /**
     * Return the value of the OPERATION column.
     * @return java.lang.String
     */
    public java.lang.String getOperation()
    {
        return this.operation;
    }

    /**
     * Set the value of the OPERATION column.
     * @param operation
     */
    public void setOperation(java.lang.String operation)
    {
        this.operation = operation;
    }

    /**
     * Return the value of the TO_ACCOUNT column.
     * @return java.lang.String
     */
    public java.lang.String getToAccount()
    {
        return this.toAccount;
    }

    /**
     * Set the value of the TO_ACCOUNT column.
     * @param toAccount
     */
    public void setToAccount(java.lang.String toAccount)
    {
        this.toAccount = toAccount;
    }

    /**
     * Return the value of the TO_AMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getToAmount()
    {
        return this.toAmount;
    }

    /**
     * Set the value of the TO_AMOUNT column.
     * @param toAmount
     */
    public void setToAmount(java.lang.Double toAmount)
    {
        this.toAmount = toAmount;
    }

    /**
     * Return the value of the BATCH_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getBatchStatus()
    {
        return this.batchStatus;
    }

    /**
     * Set the value of the BATCH_STATUS column.
     * @param batchStatus
     */
    public void setBatchStatus(java.lang.String batchStatus)
    {
        this.batchStatus = batchStatus;
    }

    /**
     * Return the value of the FROM_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getFromCurrency()
    {
        return this.fromCurrency;
    }

    /**
     * Set the value of the FROM_CURRENCY column.
     * @param fromCurrency
     */
    public void setFromCurrency(java.lang.String fromCurrency)
    {
        this.fromCurrency = fromCurrency;
    }

    /**
     * Return the value of the TO_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getToCurrency()
    {
        return this.toCurrency;
    }

    /**
     * Set the value of the TO_CURRENCY column.
     * @param toCurrency
     */
    public void setToCurrency(java.lang.String toCurrency)
    {
        this.toCurrency = toCurrency;
    }

    /**
     * Return the value of the CHARGE_CURRENCY column.
     * @return java.lang.String
     */
    public java.lang.String getChargeCurrency()
    {
        return this.chargeCurrency;
    }

    /**
     * Set the value of the CHARGE_CURRENCY column.
     * @param chargeCurrency
     */
    public void setChargeCurrency(java.lang.String chargeCurrency)
    {
        this.chargeCurrency = chargeCurrency;
    }

    /**
     * Return the value of the TOTAL_CHARGESAMOUNT column.
     * @return java.lang.Double
     */
    public java.lang.Double getTotalChargesamount()
    {
        return this.totalChargesamount;
    }

    /**
     * Set the value of the TOTAL_CHARGESAMOUNT column.
     * @param totalChargesamount
     */
    public void setTotalChargesamount(java.lang.Double totalChargesamount)
    {
        this.totalChargesamount = totalChargesamount;
    }

    /**
     * Return the value of the COMPANY_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getCompanyName()
    {
        return this.companyName;
    }

    /**
     * Set the value of the COMPANY_NAME column.
     * @param companyName
     */
    public void setCompanyName(java.lang.String companyName)
    {
        this.companyName = companyName;
    }

    /**
     * Return the value of the FILLER column.
     * @return java.lang.String
     */
    public java.lang.String getFiller()
    {
        return this.filler;
    }

    /**
     * Set the value of the FILLER column.
     * @param filler
     */
    public void setFiller(java.lang.String filler)
    {
        this.filler = filler;
    }

    /**
     * Return the value of the BATCH_RESULT column.
     * @return java.lang.String
     */
    public java.lang.String getBatchResult()
    {
        return this.batchResult;
    }

    /**
     * Set the value of the BATCH_RESULT column.
     * @param batchResult
     */
    public void setBatchResult(java.lang.String batchResult)
    {
        this.batchResult = batchResult;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof FileRequest))
            return false;
        FileRequest that = (FileRequest) rhs;
        if (this.getBatchId() == null || that.getBatchId() == null)
            return false;
        return (this.getBatchId().equals(that.getBatchId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int batchIdValue = this.getBatchId() == null ? 0 : this.getBatchId().hashCode();
            result = result * 37 + batchIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

}
