/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jan 02 12:58:34 CST 2007 by MyEclipse Hibernate Tool.
 */
package app.cib.bo.flow;

import java.io.Serializable;

/**
 * A class that represents a row in the FLOW_WORK_HIS table. 
 * You can customize the behavior of this class by editing the class, {@link FlowWorkHis()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractFlowWorkHis 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String workId;

    /** The value of the flowProcessHis association. */
    private FlowProcessHis flowProcessHis;

    /** The value of the simple workCreator property. */
    private java.lang.String workCreator;

    /** The value of the simple workCreatorName property. */
    private java.lang.String workCreatorName;

    /** The value of the simple workCreateTime property. */
    private java.util.Date workCreateTime;

    /** The value of the simple approveLevel property. */
    private java.lang.String approveLevel;

    /** The value of the simple levelFinishCount property. */
    private java.lang.Integer levelFinishCount;

    /** The value of the simple assignedDealer property. */
    private java.lang.String assignedDealer;

    /** The value of the simple workDealer property. */
    private java.lang.String workDealer;

    /** The value of the simple workDealerName property. */
    private java.lang.String workDealerName;

    /** The value of the simple dealBeginTime property. */
    private java.util.Date dealBeginTime;

    /** The value of the simple dealEndTime property. */
    private java.util.Date dealEndTime;

    /** The value of the simple dealAction property. */
    private java.lang.String dealAction;

    /** The value of the simple dealMemo property. */
    private java.lang.String dealMemo;

    /** The value of the simple workStatus property. */
    private java.lang.String workStatus;

    /**
     * Simple constructor of AbstractFlowWorkHis instances.
     */
    public AbstractFlowWorkHis()
    {
    }

    /**
     * Constructor of AbstractFlowWorkHis instances given a simple primary key.
     * @param workId
     */
    public AbstractFlowWorkHis(java.lang.String workId)
    {
        this.setWorkId(workId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getWorkId()
    {
        return workId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param workId
     */
    public void setWorkId(java.lang.String workId)
    {
        this.hashValue = 0;
        this.workId = workId;
    }

    /**
     * Return the value of the PROC_ID column.
     * @return FlowProcessHis
     */
    public FlowProcessHis getFlowProcessHis()
    {
        return this.flowProcessHis;
    }

    /**
     * Set the value of the PROC_ID column.
     * @param flowProcessHis
     */
    public void setFlowProcessHis(FlowProcessHis flowProcessHis)
    {
        this.flowProcessHis = flowProcessHis;
    }

    /**
     * Return the value of the WORK_CREATOR column.
     * @return java.lang.String
     */
    public java.lang.String getWorkCreator()
    {
        return this.workCreator;
    }

    /**
     * Set the value of the WORK_CREATOR column.
     * @param workCreator
     */
    public void setWorkCreator(java.lang.String workCreator)
    {
        this.workCreator = workCreator;
    }

    /**
     * Return the value of the WORK_CREATOR_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getWorkCreatorName()
    {
        return this.workCreatorName;
    }

    /**
     * Set the value of the WORK_CREATOR_NAME column.
     * @param workCreatorName
     */
    public void setWorkCreatorName(java.lang.String workCreatorName)
    {
        this.workCreatorName = workCreatorName;
    }

    /**
     * Return the value of the WORK_CREATE_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getWorkCreateTime()
    {
        return this.workCreateTime;
    }

    /**
     * Set the value of the WORK_CREATE_TIME column.
     * @param workCreateTime
     */
    public void setWorkCreateTime(java.util.Date workCreateTime)
    {
        this.workCreateTime = workCreateTime;
    }

    /**
     * Return the value of the APPROVE_LEVEL column.
     * @return java.lang.String
     */
    public java.lang.String getApproveLevel()
    {
        return this.approveLevel;
    }

    /**
     * Set the value of the APPROVE_LEVEL column.
     * @param approveLevel
     */
    public void setApproveLevel(java.lang.String approveLevel)
    {
        this.approveLevel = approveLevel;
    }

    /**
     * Return the value of the LEVEL_FINISH_COUNT column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevelFinishCount()
    {
        return this.levelFinishCount;
    }

    /**
     * Set the value of the LEVEL_FINISH_COUNT column.
     * @param levelFinishCount
     */
    public void setLevelFinishCount(java.lang.Integer levelFinishCount)
    {
        this.levelFinishCount = levelFinishCount;
    }

    /**
     * Return the value of the ASSIGNED_DEALER column.
     * @return java.lang.String
     */
    public java.lang.String getAssignedDealer()
    {
        return this.assignedDealer;
    }

    /**
     * Set the value of the ASSIGNED_DEALER column.
     * @param assignedDealer
     */
    public void setAssignedDealer(java.lang.String assignedDealer)
    {
        this.assignedDealer = assignedDealer;
    }

    /**
     * Return the value of the WORK_DEALER column.
     * @return java.lang.String
     */
    public java.lang.String getWorkDealer()
    {
        return this.workDealer;
    }

    /**
     * Set the value of the WORK_DEALER column.
     * @param workDealer
     */
    public void setWorkDealer(java.lang.String workDealer)
    {
        this.workDealer = workDealer;
    }

    /**
     * Return the value of the WORK_DEALER_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getWorkDealerName()
    {
        return this.workDealerName;
    }

    /**
     * Set the value of the WORK_DEALER_NAME column.
     * @param workDealerName
     */
    public void setWorkDealerName(java.lang.String workDealerName)
    {
        this.workDealerName = workDealerName;
    }

    /**
     * Return the value of the DEAL_BEGIN_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getDealBeginTime()
    {
        return this.dealBeginTime;
    }

    /**
     * Set the value of the DEAL_BEGIN_TIME column.
     * @param dealBeginTime
     */
    public void setDealBeginTime(java.util.Date dealBeginTime)
    {
        this.dealBeginTime = dealBeginTime;
    }

    /**
     * Return the value of the DEAL_END_TIME column.
     * @return java.util.Date
     */
    public java.util.Date getDealEndTime()
    {
        return this.dealEndTime;
    }

    /**
     * Set the value of the DEAL_END_TIME column.
     * @param dealEndTime
     */
    public void setDealEndTime(java.util.Date dealEndTime)
    {
        this.dealEndTime = dealEndTime;
    }

    /**
     * Return the value of the DEAL_ACTION column.
     * @return java.lang.String
     */
    public java.lang.String getDealAction()
    {
        return this.dealAction;
    }

    /**
     * Set the value of the DEAL_ACTION column.
     * @param dealAction
     */
    public void setDealAction(java.lang.String dealAction)
    {
        this.dealAction = dealAction;
    }

    /**
     * Return the value of the DEAL_MEMO column.
     * @return java.lang.String
     */
    public java.lang.String getDealMemo()
    {
        return this.dealMemo;
    }

    /**
     * Set the value of the DEAL_MEMO column.
     * @param dealMemo
     */
    public void setDealMemo(java.lang.String dealMemo)
    {
        this.dealMemo = dealMemo;
    }

    /**
     * Return the value of the WORK_STATUS column.
     * @return java.lang.String
     */
    public java.lang.String getWorkStatus()
    {
        return this.workStatus;
    }

    /**
     * Set the value of the WORK_STATUS column.
     * @param workStatus
     */
    public void setWorkStatus(java.lang.String workStatus)
    {
        this.workStatus = workStatus;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof FlowWorkHis))
            return false;
        FlowWorkHis that = (FlowWorkHis) rhs;
        if (this.getWorkId() == null || that.getWorkId() == null)
            return false;
        return (this.getWorkId().equals(that.getWorkId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int workIdValue = this.getWorkId() == null ? 0 : this.getWorkId().hashCode();
            result = result * 37 + workIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
