package app.cib.bo.flow;
// Generated by MyEclipse - Hibernate Tools



/**
 * FlowProcess generated by MyEclipse - Hibernate Tools
 */
public class FlowProcess extends AbstractFlowProcess implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -1025168493832845464L;

	/** default constructor */
    public FlowProcess() {
    }

	/** minimal constructor */
    public FlowProcess(String procId) {
        super(procId);
    }

}
